titulos = (
    "Os Vingadores",
    "Os Vingadores - A Era de Ultron",
    "Os Vingadores - Ultimato",
    "Capitão América",
    "Capitão América - Soldado Invernal",
    "Capitão América - Guerra Civil",
    "Capitã Marvel",
    "Pantera Negra",
    "Guardiões da Galaxia - Vol. 1",
    "Guardiões da Galaxia - Vol. 2",
    "Homem de Ferro",
    "Homem de Ferro 2",
    "Homem de Ferro 3",
    "Batman V. Superman",
    "Liga da Justiça",
    "Mulher Maravilha",
    "It - A Coisa",
    "Godzilla",
    "Quarteto Fantástico",
    "Doutor Estranho",
    "Homem-Formiga",
    "Homem-Formiga e a Vespa",
    "Matrix Reloaded",
    "Os Trapalhões",
    "A Morte te dá Parabéns",
    "Avatar",
    "A Morte te dá Parabéns 2",
    "Us - Nós",
    "Corra!",
    "Homem-Aranha",
    "Homem-Aranha 2",
    "Homem-Aranha 3",
    "O Espetacular Homem-Aranha",
    "O Espetacular Homem-Aranha 2",
    "Homem-Aranha no Aranhaverso",
    "Homem-Aranha - De volta ao lar",
    "Homem-Aranha - Longe de Casa",
    "Vida de Inseto",
    "O Pequeno Stuart Little",
    "Formiguinhaz",
    "Frozen",
    "Viva - A Vida é uma Festa",
    "Valente",
    "Coração Valente",
    "Batman e Robin",
    "Superman - O Retorno",
    "O Homem de Aço",
    "Jovens Titans em Ação",
    "King-Kong",
    "Harry Potter e a Pedra Filosofal",
    "Harry Potter e a Câmara Secreta",
    "Harry Potter e os Prisioneiros de Askaban",
    "Harry Potter e o Cálice de Fogo",
    "Harry Potter e o Enigma do Principe",
    "Harry Potter e as Reliquias da Morte: Parte 1",
    "Jogos Vorazes",
    "Jogos Vorazes: Em chamas",
    "Jogos Vorazes: A Esperança - Parte 1",
    "Jogos Vorazes: A Esperança - O Final",
    "Eu Sou o Numero 4",
    "Moana: Um Mar de Aventuras",
    "Divergente",
    "Velozes e Furiosos",
    "+ Velozes e + Furiosos",
    "Velozes e Furiosos - Desafio em Tóquio",
    "Velozes e Furiosos 4",
    "Velozes e Furiosos 5 - Operação Rio",
    "Velozes e Furiosos 6",
    "Velozes e Furiosos 7",
    "Velozes e Furiosos 8",
    "Assassin's Creed",
    "Guerra Mundial Z",
    "Zumbilandia",
    "Invocação do Mal",
    "Invocação do Mal 2",
    "A Freira",
    "Annabelle",
    "Annabelle 2",
    "A Maldição da Chorona",
    "Aquaman",
    "Esquadrão Suicida",
    "Coringa",
    "Venom",
    "Thor",
    "Thor: O Mundo Sobrio",
    "X-Men - O Filme",
    "X-Men 2",
    "X-Men 3: O Confronto Final",
    "X-Men: Primeira Classe",
    "X-Men: Dias de um Futuro Esquecido",
    "X-Men: Apocalipse",
    "X-Men: Fênix Negra"
    "X-Men: Origens Wolverine",
    "Wolverine: Imortal",
    "Maze Runner: Correr ou Morrer",
    "Maze Runner: Prova de Fogo",
    "Maze Runner: A Cura Mortal"
    "A Múmia",
    "O Exorcista",
    "O Exorcismo de Emily Rose",
    "O Ultimo Exorcismo",
    "O Ultimo Mestre do Ar",
    "Fragmentado",
    "Corpo Fechado",
    "Vidro",
    "O Sexto Sentido",
    "Imortais",
    "Passageiros",
    "A Bussola de Ouro",
    "Branca de Neve e os Sete Anões",
    "Pinóquio",
    "Fantasia",
    "Dumbo",
    "Bambi",
    "Alô Amigos",
    "Você já foi à Bahia?",
    "Música, Maestro",
    "Como é Bom se Divertir",
    "Tempo de Melodia",
    "Cinderela",
    "Alice no País das Maravilhas",
    "Peter Pan",
    "A Dama e o Vagabundo",
    "A Bela Adormecida",
    "101 Dálmatas",
    "Mogli: O Menino Lobo",
    "Aristogatas",
    "Robin Hood",
    "As Aventuras do Ursinho Pooh",
    "O Cão e a Raposa",
    "O Caldeirão Mágico",
    "Oliver e sua Turma",
    "A Pequena Sereia",
    "A Bela e a Fera",
    "Aladdin",
    "Pocahontas",
    "O Corcunda de Notre Dame",
    "Hécules",
    "Mulan",
    "Tarzan",
    "Fantasia 2000",
    "A Nova Onda do Imperador",
    "Atlantis: O Reino Perdido",
    "Lilo & Stitch",
    "Planeta Tesouro",
    "Irmão Urso",
    "Nem que a Vaca Tussa",
    "O Galinho Chicken Little",
    "A Família do Futuro",
    "Bolt: O Supercão",
    "A Princesa e o Sapo",
    "Enrolados",
    "Detona Ralph",
    "Frozen: Uma Aventura Congelante",
    "Operação Big Hero",
    "Zootopia: Essa Cidade é o Bicho",
    "A Familia do Futuro",
    "WiFi-Ralph",
    "Meu Amigo, o Dragão",
    "A Volta ao Mundo em 80 Minutos",
    "Hollywood em Festa",
    "Pela Porta de Serviço",
    "DuckTales, o Filme: O Tesouro da Lâmpada Perdida",
    "Pateta: O Filme",
    "Doug: O Filme",
    "Tigrão: O Filme",
    "Pateta 2 - Radicalmente Pateta",
    "Hora do Recreio",
    "Peter Pan: De Volta à Terra do Nunca",
    "Mogli: O Menino Lobo 2",
    "Leitão: O Filme",
    "O Cãozinho Esperto",
    "Mickey, Donald e Pateta: Os Três Mosqueteiros",
    "Pooh e o Efalante",
    "Bambi 2",
    "Selvagem",	
    "Tinker Bell: Uma Aventura no Mundo das Fadas",
    "Tinker Bell e o Tesouro Perdido",
    "Tinker Bell e o Resgate da Fada",
    "Tinker Bell: O Segredo das Fadas",
    "Aviões",
    "Tinker Bell: Fadas e Piratas",
    "Aviões 2: Heróis de Fogo ao Resgate",
    "Tinker Bell e o Monstro da Terra do Nunca",
    "Toy Story 2",
    "Monstros S.A.",
    "Procurando Nemo",
    "Os Incríveis",
    "Carros",
    "Ratatouille",
    "WALL-E",
    "Up: Altas Aventuras",
    "Carros 2",
    "Universidade Monstros",
    "O Bom Dinossauro",
    "Divertida Mente",
    "Procurando Dory",
    "Carros 3",
    "Viva - A Vida É uma Festa",
    "Os Incríveis 2",
    "O Estranho Mundo de Jack",
    "James e o Pêssego Gigante",
    "Frankenweenie",
    "Os Fantasmas de Scrooge",
    "Marte Precisa de Mães",
    "O Serviço de Entregas da Kiki",
    "Princesa Mononoke",
    "A Viagem de Chihiro",
    "O Reino dos Gatos",
    "O Castelo Animado",
    "Ponyo: Uma Amizade que Veio do Mar",
    "Contos de Terramar",
    "O Mundo dos Pequeninos",
    "A Torradeira Valente",
    "O Cavaleiro das Arábias",
    "A Torradeira Valente Vai a Marte",
    "A Tartaruga Manuelita",
    "A Torradeira Valente Vai à Escola",
    "Pokémon 4: Viajantes do Tempo",
    "Heróis Pokémon",
    "Valiant: Um Herói que Vale a Pena",
    "Selvagem",
    "Turma da Mônica: Uma Aventura no Tempo",
    "Romeu: O Vira-Lata Atrapalhado",
    "Gnomeu e Julieta",
    "A Volta de Mary Poppins",
    "Kim Possible",
    "A Fuga das Galinhas",
    "Shrek",
    "Shrek 2",
    "O Espanta Tubarões",
    "Madagascar",
    "Os Sem Floresta",
    "Por Água Abaixo",
    "Shrek Terceiro",
    "Bee Movie",
    "Kung Fu Panda",
    "Madagascar: 2",
    "Monstros vs. Alienígenas",
    "Como Treinar o Seu Dragão",
    "Shrek para Sempre",
    "Megamente",
    "Kung Fu Panda 2",
    "O Gato de Botas",
    "Madagascar 3",
    "A Origem dos Guardiões",
    "Os Croods",
    "Turbo",
    "As Aventuras de Peabody e Sherman",
    "Como Treinar o Seu Dragão 2",
    "Os Pinguins de Madagascar",
    "Cada um na Sua Casa",
    "Kung Fu Panda 3",
    "Trolls",
    "O Poderoso Chefinho",
    "As Aventuras do Capitão Cueca",
    "Como Treinar o Seu Dragão 3",
    "Alvin e os Esquilos",
    "A Era do Gelo",
    "Duro de Matar",
    "Esqueceram de Mim",
    "Clube da Luta",
    "Rio",
    "Rio 2",
    "Titanic",
    "Deadpool",
    "Deadpool 2",
    "Uma Noite no Museu",
    "Quarteto Fantástico e o Surfista Prateado",
    "Independece Day",
    "Kigsman: Serviço Secreto",
    "Alien vs Predador",
    "A Era do Gelo 2: O Degelo",
    "O Predador",
    "Pequenos Invasores",
    "Dr. Dolittle",
    "Atrás das Linhas Inimigas",
    "Tora! Tora! Tora!",
    "Uma Secretária do Futuro",
    "Elektra",
    "Náufrago",
    "Demolidor - O Homem sem Medo",
    "Perdido em Marte",
    "A Culpa é das Estrelas",
    "O Regresso",
    "O Diabo Veste Prada",
    "Alien - o Oitavo Passageiro",
    "Um sonho de Liberdade",
    "O Poderoso Chefão",
    "O Poderoso Chefão II",
    "Batman - O Cavaleiro das Trevas",
    "12 Homens e uma Sentença",
    "A Lista de Schindler",
    "Pulp Fiction: Tempo de Violência",
    "O Senhor dos Anéis: O Retorno do Rei",
    "Três homens em Conflito",
    "Clube da Luta",
    "O Senhor dos Anéis: A Sociedade do Anel",
    "Forrest Gump: O Contador de Histórias",
    "Star Wars: Episódio V - O Império Contra-Ataca",
    "A Origem",
    "O Senhor dos Anéis: As Duas Torres",
    "Um Estranho no Ninho",
    "Os Bons Companheiros",
    "Matrix",
    "Os Sete Samurais",
    "Guerra nas Estrelas - Uma Nova Esperança",
    "Cidade de Deus",
    "Seven: Os Sete Crimes Capitais",
    "O Silêncio dos Inocentes",
    "A Felicidade Não se Compra",
    "A Vida é Bela",
    "O Profissional",
    "O Resgate do Soldado Ryan",
    "A Viagem de Chihiro",
    "A Outra História Americana",
    "Era uma Vez no Oeste",
    "Interestelar",
    "À Espera de um Milagre",
    "Psicose",
    "Casablanca",
    "Luzes da Cidade",
    "Intocáveis",
    "Os Tempos Modernos",
    "O Pianista",
    "Indiana Jones e Os Caçadores da Arca Perdida",
    "Os Infiltrados",
    "Janela Indiscreta",
    "O Exterminador do Futuro 2: O Julgamento Final",
    "De Volta para o Futuro",
    "Whiplash: Em Busca da Perfeição",
    "Gladiador",
    "O Grande Truque",
    "O Rei Leão",
    "Amnésia",
    "Apocalypse Now",
    "O Grande Ditador",
    "Crepúsculo dos Deuses",
    "Cinema Paradiso",
    "Dr. Fantástico",
    "A Vida dos Outros",
    "O Túmulo dos Vagalumes",
    "Glória Feita de Sangue",
    "Django Livre",
    "O Iluminado",
    "Wall-E",
    "Beleza Americana",
    "Blade Runner 2049",
    "Batman: O Cavaleiro das Trevas Ressurge",
    "Princesa Mononoke",
    "Oldboy",
    "Aliens, O Resgate",
    "Testemunha de Acusação",
    "Era Uma Vez na América",
    "O barco: Inferno no Mar",
    "Dangal",
    "O Cidadão Kane",
    "Um Corpo que Cai",
    "Intriga Internacional",
    "Star Wars: Episódio VI - O Retorno de Jedi",
    "Cães de Aluguel",
    "M, O Vampiro de Dusseldorf",
    "Réquiem Para um Sonho",
    "Como Estrelas na Terra",
    "O Fabuloso Destino de Amélie Poulain",
    "Kimi no na wa.",
    "Laranja Mecânica",
    "Lawrence da Arábia",
    "Amadeus",
    "Pacto de Sangue",
    "Brilho Eterno de uma Mente Sem Lembranças",
    "Taxi Driver",
    "O Sol é Para Todos",
    "Nascido para Matar",
    "2001: Uma Odisseia no Espaço",
    "Cantando na Chuva",
    "Toy Story",
    "3 Idiots",
    "Golpe de Mestre",
    "Toy Story 3",
    "Bastardos Inglórios",
    "Ladrões de Bicicletas",
    "O Garoto",
    "Dunkirk",
    "Monty Python em Busca do Cálice Sagrado",
    "Gênio Indomável",
    "A Caça",
    "Por Uns Dólares a Mais",
    "Los Angeles: Cidade Proibida",
    "Scarface",
    "Se Meu Apartamento Falasse",
    "Metrópolis",
    "A Separação",
    "Rashomon",
    "Indiana Jones e a Última Cruzada",
    "A Malvada",
    "Yojimbo - O Guarda-Costas",
    "Meu Pai e Meu Filho",
    "Up: Altas Aventuras",
    "Batman Begins",
    "Quanto Mais Quente Melhor",
    "O Tesouro da Sierra Madre",
    "Os Imperdoáveis",
    "A Queda! As Últimas Horas de Hitler",
    "Duro de Matar",
    "Touro Indomável",
    "Fogo Contra Fogo",
    "Filhos do Paraíso",
    "Fugindo do Inferno",
    "Viver",
    "Chinatown",
    "O Labirinto do Fauno",
    "Meu Amigo Totoro",
    "Incêndios",
    "Ran",
    "Julgamento em Nuremberg",
    "Em Busca do Ouro",
    "O Segredo dos seus Olhos",
    "Divertida Mente",
    "O Castelo Animado",
    "Sindicato de Ladrões",
    "A Ponte do Rio Kwai",
    "O Sétimo Selo",
    "O Quarto de Jack",
    "Jogos, Trapaças e Dois Canos Fumegantes",
    "A Mulher Faz o Homem",
    "Uma Mente Brilhante",
    "Cassino",
    "Blade Runner, o Caçador de Androides",
    "O Homem Elefante",
    "V de Vingança",
    "O Lobo de Wall Street",
    "General",
    "Guerreiro",
    "Disque M para Matar",
    "Trainspotting - Sem limites",
    "Gran Torino",
    "...E o Vento Levou",
    "Aurora",
    "O Franco Atirador",
    "O Sexto Sentido",
    "Fargo - Uma Coméedia de erros",
    "O Enigma de Outro Mundo",
    "Andrey Rublev",
    "Onde os Fracos Não Têm Vez",
    "O Grande Lebowski",
    "Procurando Nemo",
    "O Bandido",
    "Era uma Vez em Tóquio",
    "Sangue Negro",
    "Rebeldia Indomável",
    "Vá e Veja",
    "Rebecca, A Mulher Inesquecível",
    "Até o Último Homem",
    "Kill Bill: Volume 1",
    "Como Treinar o Seu Dragão",
    "O Martírio de Joana D'Arc",
    "Mary e Max: Uma Amizade Diferente",
    "Garota Exemplar",
    "Ilha do Medo",
    "La La Land: Cantando Emoções",
    "Na Natureza Selvagem",
    "Monty Python: A Vida de Brian",
    "Aconteceu Naquela Noite",
    "Relatos Selvagens",
    "Logan",
    "Platoon",
    "O Salário do Medo",
    "Hotel Ruanda",
    "Rede de Intrigas",
    "Em Nome do Pai",
    "Rush: No Limite da Emoção",
    "Conta Comigo",
    "A Wednesday",
    "Thor: Ragnarok",
    "Quando Duas Mulheres Pecam",
    "Ben-Hur",
    "O Grande Hotel Budapeste",
    "Os Incompreendidos",
    "Memórias de um Assassino",
    "12 Anos de Escravidão",
    "Mad Max: Estrada da Fúria",
    "Menina de Ouro",
    "Spotlight: Segredos Revelados",
    "Stalker",
    "O Show de Truman",
    "Amores Brutos",
    "Butch Cassidy",
    "Sempre ao Seu Lado",
    "Nausicaä do Vale do Vento",
    "A Princesa Prometida",
    "Antes do Amanhecer",
    "Relíquia Macabra (O Falcão Maltês)",
    "Lua de Papel",
    "Noites de Cabíria",
    "Os Suspeitos",
    "Harry Potter e as Relíquias da Morte: Parte 2",
    "Vinhas da Ira",
    "Rocky: Um Lutador",
    "Prenda-me Se For Capaz",
    "As Diabólicas",
    "A Marca da Maldade",
    "Gandhi",
    "Monstros S.A.",
    "Barry Lyndon",
    "Noivo Neurótico, Noiva Nervosa",
    "O Exterminador do Futuro",
    "Star Wars: Episódio VII: O Despertar da Força",
    "O Ultimato Bourne",
    "O Mágico de Oz",
    "Feitiço do Tempo",
    "O Ódio",
    "Tubarão",
    "Os Melhores Anos de Nossas Vidas",
    "Os 12 Macacos",
    "Conflitos Internos",
    "Amor à Flor da Pele",
    "Paris, Texas",
    "Histórias Cruzadas",
    "A Bela e a Fera",
    "Sociedade dos Poetas Mortos",
    "A Criada",
    "A Batalha de Argel",
    "Piratas do Caribe: A Maldição do Pérola Negra",
    "Gangs of Wasseypur",
    "Um Dia de Cão",
    "Branca de Neve e os Sete Anões",
    "Pinóquio",
    "Fantasia",
    "O Dragão Relutante",
    "Dumbo",
    "Bambi",
    "Vitória Através do Poder Aéreo",
    "Alô, amigos",
    "Você já foi à Bahia?",
    "Música, Maestro!",
    "A Canção do Sul",
    "Como é Bom se Divertir",
    "Tempo de Melodia",
    "Meu Querido Carneirinho",
    "As Aventuras de Ichabod e Sr. Sapo",
    "Cinderela",
    "A Ilha do Tesouro",
    "Alice no País das Maravilhas",
    "Robin Hood, o Justiceiro",
    "Peter Pan",
    "Entre a Espada e a Rosa",
    "20.000 Léguas Submarinas",
    "A Dama e o Vagabundo",
    "Têmpera de bravos",
    "Audácia de um rebelde",
    "Meu Querido Companheiro",
    "A Bela Adormecida",
    "A lenda dos anões mágicos",
    "Felpudo, o Cão Feiticeiro",
    "O Mundo Fabuloso do Circo",
    "A Espada de um Bravo",
    "Pollyanna",
    "O Incrível Zorro",
    "Os Dez Ousados",
    "A Cidadela dos Robinson",
    "101 Dálmatas",
    "O Fantástico Super-Homem",
    "Operação Cupido",
    "Nikki, O Cão Selvagem do Norte",
    "Meu Leal Companheiro",
    "O Mundo Encantado dos Brinquedos",
    "Bon-Voyage, Enfim Paris",
    "O Campeão",
    "Quase Anjos",
    "A Montanha do Lobo Sanguinário",
    "As Grandes Aventuras do Capitão Grant",
    "Na trilha dos Apaches",
    "Doce Verão dos Meus Sonhos",
    "A Incrível Jornada",
    "A Espada Era a Lei",
    "O Segredo das Esmeraldas Negras",
    "Mary Poppins",
    "Em busca da aventura",
    "Aquele Gato Danado",
    "Nunca é tarde para amar",
    "Eu Acredito em Gnomos",
    "Mogli - O Menino Lobo",
    "Se meu fusca falasse",
    "O Computador de Tênis"
    "Percy Jackson e o Ladrão de Raios",
    "Robocop",
    "Minority Report",
    "Os Simpsons",
    "Arquivo X",
    "Marley e Eu",
    "A Paixão de Cristo",
    "Cruzada",
    "Guerra é Guerra"
    "Victor Freinkeinstein",
    "Birdman",
    "Bird Box",
    "Eu, Robô",
    "O Fada do Dente",
    "500 Dias com Ela",
    "Garota Infernal",
    "Transformers",
    "Esquadrão Classe A",
    "DPA - Detetives do Prédio Azul"
)

paises = (
    "Andorra",
    "Emirados Árabes Unidos",
    "Afeganistão",
    "Antígua e Barbuda",
    "Anguilla",
    "Albânia",
    "Armênia",
    "Angola",
    "Antártica",
    "Argentina",
    "Samoa Americana",
    "Áustria",
    "Austrália",
    "Aruba",
    "Azerbaijão",
    "Bósnia e Herzegovina",
    "Barbados",
    "Bangladesh",
    "Bélgica",
    "Burkina Faso",
    "Bulgária",
    "Barém",
    "Burundi",
    "Benin",
    "São Bartolomeu",
    "Bermuda",
    "Brunei",
    "Bolívia",
    "Brasil",
    "Bahamas",
    "Butão",
    "Ilha Bouvet",
    "Botswana",
    "Belarus",
    "Belize",
    "Canadá",
    "Ilhas Cocos (Keeling)",
    "Congo, República Democrática do",
    "República Centro-Africana",
    "Congo, República do",
    "Suíça",
    "Costa do Marfim",
    "Ilhas Cook",
    "Chile",
    "Camarões",
    "China",
    "Colômbia",
    "Costa Rica",
    "Cuba",
    "Cabo Verde",
    "Curaçao",
    "Ilha Christmas",
    "Chipre",
    "República Tcheca",
    "Alemanha",
    "Djibuti",
    "Dinamarca",
    "Dominica",
    "República Dominicana",
    "Argélia",
    "Equador",
    "Estônia",
    "Egito",
    "Saara Ocidental",
    "Eritréia",
    "Espanha",
    "Etiópia",
    "Finlândia",
    "Fiji",
    "Ilhas Falkland (Malvinas)",
    "Micronésia, Estados Federados da",
    "Ilhas Feroe",
    "França",
    "França Metropolitana",
    "Gabão",
    "Reino Unido",
    "Grenada",
    "Geórgia",
    "Guiana Francesa",
    "Guernsey",
    "Gana",
    "Gibraltar",
    "Greenland",
    "Gâmbia",
    "Guiné",
    "Guadelupe",
    "Guiné Equatorial",
    "Grécia",
    "Geórgia do Sul e Ilhas",
    "Guatemala",
    "Guam",
    "Guiné-Bissau",
    "Guiana",
    "Hong Kong",
    "Ilhas Heard and McDonald",
    "Honduras",
    "Croácia",
    "Haiti",
    "Hungria",
    "Indonésia",
    "Irlanda",
    "Israel",
    "Ilha de Man",
    "Índia",
    "Iraque",
    "Irã",
    "Islândia",
    "Itália",
    "Jersey",
    "Jamaica",
    "Jordânia",
    "Japão",
    "Quênia",
    "Quirguistão",
    "Camboja",
    "Kiribati",
    "Cômoros",
    "São Cristóvão e Nevis",
    "Coreia do Norte",
    "Coreia do Sul",
    "Kuwait",
    "Ilhas Caiman",
    "Cazaquistão",
    "Laos",
    "Líbano",
    "Santa Lúcia",
    "Liechtenstein",
    "Sri Lanka",
    "Libéria",
    "Lesoto",
    "Lituânia",
    "Luxemburgo",
    "Letônia",
    "Líbia",
    "Marrocos",
    "Mônaco",
    "Moldova",
    "Montenegro",
    "Saint Martin",
    "Madagascar",
    "Ilhas Marshall",
    "Macedônia",
    "Mali",
    "Birmânia",
    "Mongólia",
    "Macao",
    "Ilhas Marianas do Norte",
    "Martinica",
    "Mauritânia",
    "Montserrat",
    "Malta",
    "Ilhas Maurício",
    "Maldivas",
    "Malawi",
    "México",
    "Malásia",
    "Moçambique",
    "Namíbia",
    "Nova Caledônia",
    "Níger",
    "Ilha Norfolk",
    "Nigéria",
    "Nicarágua",
    "Holanda",
    "Noruega",
    "Nepal",
    "Nauru",
    "Niue",
    "Nova Zelândia",
    "Omã",
    "Panamá",
    "Peru",
    "Polinésia Francesa",
    "Papua Nova Guiné",
    "Filipinas",
    "Paquistão",
    "Polônia",
    "Saint Pierre e Miquelon",
    "Ilhas Pitcairn",
    "Porto Rico",
    "Faixa de Gaza",
    "Cisjordânia",
    "Portugal",
    "Palau",
    "Paraguai",
    "Qatar",
    "Reunião",
    "Romênia",
    "Sérvia",
    "Rússia",
    "Ruanda",
    "Arábia Saudita",
    "Ilhas Salomão",
    "Seicheles",
    "Sudão",
    "Suécia",
    "Cingapura",
    "Eslovênia",
    "Svalbard",
    "Eslováquia",
    "Serra Leoa",
    "San Marino",
    "Senegal",
    "Somália",
    "Suriname",
    "Sudão do Sul",
    "São Tomé e Príncipe",
    "El Salvador",
    "São Martinho",
    "Síria",
    "Suazilândia",
    "Ilhas Turks e Caicos",
    "Chad",
    "Sul da França e Antártica",
    "Togo",
    "Tailândia",
    "Tadjiquistão",
    "Toquelau",
    "Timor-Leste",
    "Turcomenistão",
    "Tunísia",
    "Tonga",
    "Turquia",
    "Trinidad e Tobago",
    "Tuvalu",
    "Taiwan",
    "Tanzânia",
    "Ucrânia",
    "Uganda",
    "Ilhas Menores Distantes dos Estados Unidos",
    "Estados Unidos",
    "Uruguai",
    "Uzbequistão",
    "Santa Sé (Cidade do Vaticano)",
    "São Vicente e Granadinas",
    "Venezuela",
    "Ilhas Virgens Britânicas",
    "Ilhas Virgens Americanas",
    "Vietnã",
    "Vanuatu",
    "Ilhas Wallis e Futuna",
    "Samoa",
    "Kosovo",
    "Iêmen",
    "Maiote",
    "África do Sul",
    "Zâmbia",
    "Zimbábue"
)

diretores = (
    "Alfred Hitchcock",
    "Orson Welles",
    "John Ford",
    "Howard Hawks",
    "Martin Scorsese",
    "Akira Kurosawa",
    "Buster Keaton",
    "Ingmar Bergman",
    "Frank Capra",
    "Federico Fellini",
    "Steven Spielberg",
    "Jean Renoir",
    "John Huston",
    "Luis Buñuel",
    "D. W. Griffith",
    "Ernst Lubitsch",
    "Robert Altman",
    "George Cukor",
    "Woody Allen",
    "Vicente Minnelli",
    "Francis Ford Coppola",
    "Michael Powell",
    "Stanley Kubrick",
    "Billy Wilder",
    "Satyajit Ray",
    "Roman Polanski",
    "François Truffaut",
    "Preston Sturges",
    "Sergei Eisenstein",
    "Fritz Lang",
    "Jean-Luc Godard",
    "Sam Peckinpah",
    "F. W. Murnau",
    "David Lean",
    "Werner Herzog",
    "Nicholas Ray",
    "Josef Von Sterberg",
    "Douglas Sirk",
    "Max Ophuls",
    "Louis Malle",
    "Sergio Leone",
    "Sidney Lumet",
    "Oliver Stone",
    "Bernardo Bertolucci",
    "Jonathan Demme",
    "Jacques Tati",
    "Otto Preminger",
    "Spike Lee",
    "Tim Burton",
    "Jerry Lewis",
    "Jon Favreau",
    "Ben Affleck",
    "Joss Whedon",
    "George Lucas",
    "Zack Snyder",
    "Christopher Nolan",
    "Sam Raimi",
    "James Wan",
    "Patty Jenkins",
    "Anthony Russo",
    "Joe Russo",
    "Lilly Wachowski",
    "Lana Wachowski",
    "Jonh Krasinsky",
    "Marc Forster",
    "Jordan Peele",
    "James Cameron",
    'M. Night Shyamalan',
    "Denis Villeneuve",
    "Richard Linklater",
    "Guilhermo Del Toro"

)