titulos = (
    "Os Vingadores",
    "Os Vingadores - A Era de Ultron",
    "Os Vingadores - Ultimato",
    "Capitão América",
    "Capitão América - Soldado Invernal",
    "Capitão América - Guerra Civil",
    "Capitã Marvel",
    "Pantera Negra",
    "Guardiões da Galaxia - Vol. 1",
    "Guardiões da Galaxia - Vol. 2",
    "Homem de Ferro",
    "Homem de Ferro 2",
    "Homem de Ferro 3",
    "Batman V. Superman",
    "Liga da Justiça",
    "Mulher Maravilha",
    "It - A Coisa",
    "Godzilla",
    "Quarteto Fantástico",
    "Doutor Estranho",
    "Homem-Formiga",
    "Homem-Formiga e a Vespa",
    "Matrix Reloaded",
    "Os Trapalhões",
    "A Morte te dá Parabéns",
    "Avatar",
    "A Morte te dá Parabéns 2",
    "Us - Nós",
    "Corra!",
    "Homem-Aranha",
    "Homem-Aranha 2",
    "Homem-Aranha 3",
    "O Espetacular Homem-Aranha",
    "O Espetacular Homem-Aranha 2",
    "Homem-Aranha no Aranhaverso",
    "Homem-Aranha - De volta ao lar",
    "Homem-Aranha - Longe de Casa",
    "Um sonho de Liberdade",
    "O Poderoso Chefão",
    "O Poderoso Chefão II",
    "Batman - O Cavaleiro das Trevas",
    "12 Homens e uma Sentença",
    "A Lista de Schindler",
    "Pulp Fiction: Tempo de Violência",
    "O Senhor dos Anéis: O Retorno do Rei",
    "Três homens em Conflito",
    "Clube da Luta",
    "O Senhor dos Anéis: A Sociedade do Anel",
    "Forrest Gump: O Contador de Histórias",
    "Star Wars: Episódio V - O Império Contra-Ataca",
    "A Origem",
    "O Senhor dos Anéis: As Duas Torres",
    "Um Estranho no Ninho",
    "Os Bons Companheiros",
    "Matrix",
    "Os Sete Samurais",
    "Guerra nas Estrelas - Uma Nova Esperança",
    "Cidade de Deus",
    "Seven: Os Sete Crimes Capitais",
    "O Silêncio dos Inocentes",
    "A Felicidade Não se Compra",
    "A Vida é Bela",
    "O Profissional",
    "O Resgate do Soldado Ryan",
    "A Viagem de Chihiro",
    "A Outra História Americana",
    "Era uma Vez no Oeste",
    "Interestelar",
    "À Espera de um Milagre",
    "Psicose",
    "Casablanca",
    "Luzes da Cidade",
    "Intocáveis",
    "Os Tempos Modernos",
    "O Pianista",
    "Indiana Jones e Os Caçadores da Arca Perdida",
    "Os Infiltrados",
    "Janela Indiscreta",
    "O Exterminador do Futuro 2: O Julgamento Final",
    "De Volta para o Futuro",
    "Whiplash: Em Busca da Perfeição",
    "Gladiador",
    "O Grande Truque",
    "O Rei Leão",
    "Amnésia",
    "Apocalypse Now",
    "O Grande Ditador",
    "Crepúsculo dos Deuses",
    "Cinema Paradiso",
    "Dr. Fantástico",
    "A Vida dos Outros",
    "O Túmulo dos Vagalumes",
    "Glória Feita de Sangue",
    "Django Livre",
    "O Iluminado",
    "Wall-E",
    "Beleza Americana",
    "Blade Runner 2049",
    "Batman: O Cavaleiro das Trevas Ressurge",
    "Princesa Mononoke",
    "Oldboy",
    "Aliens, O Resgate",
    "Testemunha de Acusação",
    "Era Uma Vez na América",
    "O barco: Inferno no Mar",
    "Dangal",
    "O Cidadão Kane",
    "Um Corpo que Cai",
    "Intriga Internacional",
    "Star Wars: Episódio VI - O Retorno de Jedi",
    "Cães de Aluguel",
    "M, O Vampiro de Dusseldorf",
    "Réquiem Para um Sonho",
    "Como Estrelas na Terra",
    "O Fabuloso Destino de Amélie Poulain",
    "Kimi no na wa.",
    "Laranja Mecânica",
    "Lawrence da Arábia",
    "Amadeus",
    "Pacto de Sangue",
    "Brilho Eterno de uma Mente Sem Lembranças",
    "Taxi Driver",
    "O Sol é Para Todos",
    "Nascido para Matar",
    "2001: Uma Odisseia no Espaço",
    "Cantando na Chuva",
    "Toy Story",
    "3 Idiots",
    "Golpe de Mestre",
    "Toy Story 3",
    "Bastardos Inglórios",
    "Ladrões de Bicicletas",
    "O Garoto",
    "Dunkirk",
    "Monty Python em Busca do Cálice Sagrado",
    "Gênio Indomável",
    "A Caça",
    "Por Uns Dólares a Mais",
    "Los Angeles: Cidade Proibida",
    "Scarface",
    "Se Meu Apartamento Falasse",
    "Metrópolis",
    "A Separação",
    "Rashomon",
    "Indiana Jones e a Última Cruzada",
    "A Malvada",
    "Yojimbo - O Guarda-Costas",
    "Meu Pai e Meu Filho",
    "Up: Altas Aventuras",
    "Batman Begins",
    "Quanto Mais Quente Melhor",
    "O Tesouro da Sierra Madre",
    "Os Imperdoáveis",
    "A Queda! As Últimas Horas de Hitler",
    "Duro de Matar",
    "Touro Indomável",
    "Fogo Contra Fogo",
    "Filhos do Paraíso",
    "Fugindo do Inferno",
    "Viver",
    "Chinatown",
    "O Labirinto do Fauno",
    "Meu Amigo Totoro",
    "Incêndios",
    "Ran",
    "Julgamento em Nuremberg",
    "Em Busca do Ouro",
    "O Segredo dos seus Olhos",
    "Divertida Mente",
    "O Castelo Animado",
    "Sindicato de Ladrões",
    "A Ponte do Rio Kwai",
    "O Sétimo Selo",
    "O Quarto de Jack",
    "Jogos, Trapaças e Dois Canos Fumegantes",
    "A Mulher Faz o Homem",
    "Uma Mente Brilhante",
    "Cassino",
    "Blade Runner, o Caçador de Androides",
    "O Homem Elefante",
    "V de Vingança",
    "O Lobo de Wall Street",
    "General",
    "Guerreiro",
    "Disque M para Matar",
    "Trainspotting - Sem limites",
    "Gran Torino",
    "...E o Vento Levou",
    "Aurora",
    "O Franco Atirador",
    "O Sexto Sentido",
    "Fargo - Uma Coméedia de erros",
    "O Enigma de Outro Mundo",
    "Andrey Rublev",
    "Onde os Fracos Não Têm Vez",
    "O Grande Lebowski",
    "Procurando Nemo",
    "O Bandido",
    "Era uma Vez em Tóquio",
    "Sangue Negro",
    "Rebeldia Indomável",
    "Vá e Veja",
    "Rebecca, A Mulher Inesquecível",
    "Até o Último Homem",
    "Kill Bill: Volume 1",
    "Como Treinar o Seu Dragão",
    "O Martírio de Joana D'Arc",
    "Mary e Max: Uma Amizade Diferente",
    "Garota Exemplar",
    "Ilha do Medo",
    "La La Land: Cantando Emoções",
    "Na Natureza Selvagem",
    "Monty Python: A Vida de Brian",
    "Aconteceu Naquela Noite",
    "Relatos Selvagens",
    "Logan",
    "Platoon",
    "O Salário do Medo",
    "Hotel Ruanda",
    "Rede de Intrigas",
    "Em Nome do Pai",
    "Rush: No Limite da Emoção",
    "Conta Comigo",
    "A Wednesday",
    "Thor: Ragnarok",
    "Quando Duas Mulheres Pecam",
    "Ben-Hur",
    "O Grande Hotel Budapeste",
    "Os Incompreendidos",
    "Memórias de um Assassino",
    "12 Anos de Escravidão",
    "Mad Max: Estrada da Fúria",
    "Menina de Ouro",
    "Spotlight: Segredos Revelados",
    "Stalker",
    "O Show de Truman",
    "Amores Brutos",
    "Butch Cassidy",
    "Sempre ao Seu Lado",
    "Nausicaä do Vale do Vento",
    "A Princesa Prometida",
    "Antes do Amanhecer",
    "Relíquia Macabra (O Falcão Maltês)",
    "Lua de Papel",
    "Noites de Cabíria",
    "Os Suspeitos",
    "Harry Potter e as Relíquias da Morte: Parte 2",
    "Vinhas da Ira",
    "Rocky: Um Lutador",
    "Prenda-me Se For Capaz",
    "As Diabólicas",
    "A Marca da Maldade",
    "Gandhi",
    "Monstros S.A.",
    "Barry Lyndon",
    "Noivo Neurótico, Noiva Nervosa",
    "O Exterminador do Futuro",
    "Star Wars: Episódio VII: O Despertar da Força",
    "O Ultimato Bourne",
    "O Mágico de Oz",
    "Feitiço do Tempo",
    "O Ódio",
    "Zootopia",
    "Tubarão",
    "Os Melhores Anos de Nossas Vidas",
    "Os 12 Macacos",
    "Conflitos Internos",
    "Amor à Flor da Pele",
    "Paris, Texas",
    "Histórias Cruzadas",
    "A Bela e a Fera",
    "Sociedade dos Poetas Mortos",
    "A Criada",
    "A Batalha de Argel",
    "Piratas do Caribe: A Maldição do Pérola Negra",
    "Gangs of Wasseypur",
    "Um Dia de Cão"
)

paises = (
    "Andorra",
    "Emirados Árabes Unidos",
    "Afeganistão",
    "Antígua e Barbuda",
    "Anguilla",
    "Albânia",
    "Armênia",
    "Angola",
    "Antártica",
    "Argentina",
    "Samoa Americana",
    "Áustria",
    "Austrália",
    "Aruba",
    "Azerbaijão",
    "Bósnia e Herzegovina",
    "Barbados",
    "Bangladesh",
    "Bélgica",
    "Burkina Faso",
    "Bulgária",
    "Barém",
    "Burundi",
    "Benin",
    "São Bartolomeu",
    "Bermuda",
    "Brunei",
    "Bolívia",
    "Brasil",
    "Bahamas",
    "Butão",
    "Ilha Bouvet",
    "Botswana",
    "Belarus",
    "Belize",
    "Canadá",
    "Ilhas Cocos (Keeling)",
    "Congo, República Democrática do",
    "República Centro-Africana",
    "Congo, República do",
    "Suíça",
    "Costa do Marfim",
    "Ilhas Cook",
    "Chile",
    "Camarões",
    "China",
    "Colômbia",
    "Costa Rica",
    "Cuba",
    "Cabo Verde",
    "Curaçao",
    "Ilha Christmas",
    "Chipre",
    "República Tcheca",
    "Alemanha",
    "Djibuti",
    "Dinamarca",
    "Dominica",
    "República Dominicana",
    "Argélia",
    "Equador",
    "Estônia",
    "Egito",
    "Saara Ocidental",
    "Eritréia",
    "Espanha",
    "Etiópia",
    "Finlândia",
    "Fiji",
    "Ilhas Falkland (Malvinas)",
    "Micronésia, Estados Federados da",
    "Ilhas Feroe",
    "França",
    "França Metropolitana",
    "Gabão",
    "Reino Unido",
    "Grenada",
    "Geórgia",
    "Guiana Francesa",
    "Guernsey",
    "Gana",
    "Gibraltar",
    "Greenland",
    "Gâmbia",
    "Guiné",
    "Guadelupe",
    "Guiné Equatorial",
    "Grécia",
    "Geórgia do Sul e Ilhas",
    "Guatemala",
    "Guam",
    "Guiné-Bissau",
    "Guiana",
    "Hong Kong",
    "Ilhas Heard and McDonald",
    "Honduras",
    "Croácia",
    "Haiti",
    "Hungria",
    "Indonésia",
    "Irlanda",
    "Israel",
    "Ilha de Man",
    "Índia",
    "Território Britânico do Oceano Índico",
    "Iraque",
    "Irã",
    "Islândia",
    "Itália",
    "Jersey",
    "Jamaica",
    "Jordânia",
    "Japão",
    "Quênia",
    "Quirguistão",
    "Camboja",
    "Kiribati",
    "Cômoros",
    "São Cristóvão e Nevis",
    "Coreia do Norte",
    "Coreia do Sul",
    "Kuwait",
    "Ilhas Caiman",
    "Cazaquistão",
    "Laos",
    "Líbano",
    "Santa Lúcia",
    "Liechtenstein",
    "Sri Lanka",
    "Libéria",
    "Lesoto",
    "Lituânia",
    "Luxemburgo",
    "Letônia",
    "Líbia",
    "Marrocos",
    "Mônaco",
    "Moldova",
    "Montenegro",
    "Saint Martin",
    "Madagascar",
    "Ilhas Marshall",
    "Macedônia",
    "Mali",
    "Birmânia",
    "Mongólia",
    "Macao",
    "Ilhas Marianas do Norte",
    "Martinica",
    "Mauritânia",
    "Montserrat",
    "Malta",
    "Ilhas Maurício",
    "Maldivas",
    "Malawi",
    "México",
    "Malásia",
    "Moçambique",
    "Namíbia",
    "Nova Caledônia",
    "Níger",
    "Ilha Norfolk",
    "Nigéria",
    "Nicarágua",
    "Holanda",
    "Noruega",
    "Nepal",
    "Nauru",
    "Niue",
    "Nova Zelândia",
    "Omã",
    "Panamá",
    "Peru",
    "Polinésia Francesa",
    "Papua Nova Guiné",
    "Filipinas",
    "Paquistão",
    "Polônia",
    "Saint Pierre e Miquelon",
    "Ilhas Pitcairn",
    "Porto Rico",
    "Faixa de Gaza",
    "Cisjordânia",
    "Portugal",
    "Palau",
    "Paraguai",
    "Qatar",
    "Reunião",
    "Romênia",
    "Sérvia",
    "Rússia",
    "Ruanda",
    "Arábia Saudita",
    "Ilhas Salomão",
    "Seicheles",
    "Sudão",
    "Suécia",
    "Cingapura",
    "Santa Helena, Ascensão e Tristão da Cunha",
    "Eslovênia",
    "Svalbard",
    "Eslováquia",
    "Serra Leoa",
    "San Marino",
    "Senegal",
    "Somália",
    "Suriname",
    "Sudão do Sul",
    "São Tomé e Príncipe",
    "El Salvador",
    "São Martinho",
    "Síria",
    "Suazilândia",
    "Ilhas Turks e Caicos",
    "Chad",
    "Sul da França e Antártica",
    "Togo",
    "Tailândia",
    "Tadjiquistão",
    "Toquelau",
    "Timor-Leste",
    "Turcomenistão",
    "Tunísia",
    "Tonga",
    "Turquia",
    "Trinidad e Tobago",
    "Tuvalu",
    "Taiwan",
    "Tanzânia",
    "Ucrânia",
    "Uganda",
    "Ilhas Menores Distantes dos Estados Unidos",
    "Estados Unidos",
    "Uruguai",
    "Uzbequistão",
    "Santa Sé (Cidade do Vaticano)",
    "São Vicente e Granadinas",
    "Venezuela",
    "Ilhas Virgens Britânicas",
    "Ilhas Virgens Americanas",
    "Vietnã",
    "Vanuatu",
    "Ilhas Wallis e Futuna",
    "Samoa",
    "Kosovo",
    "Iêmen",
    "Maiote",
    "África do Sul",
    "Zâmbia",
    "Zimbábue"
)

diretores = (
    
)