#include "dados.h"

const char *const filmes[] = {
    "Os Vingadores",
    "Os Vingadores - A Era de Ultron",
    "Os Vingadores - Ultimato",
    "Capitão América",
    "Capitão América - Soldado Invernal",
    "Capitão América - Guerra Civil",
    "Capitã Marvel",
    "Pantera Negra",
    "Guardiões da Galaxia",
    "Guardiões da Galaxia - Vol. 2",
    "Homem de Ferro",
    "Homem de Ferro 2",
    "Homem de Ferro 3",
    "Batman Vs. Superman",
    "Liga da Justiça",
    "Mulher Maravilha",
    "It - A Coisa",
    "Godzilla",
    "Quarteto Fantástico",
    "Doutor Estranho",
    "Homem-Formiga",
    "Homem-Formiga e a Vespa",
    "Matrix Reloaded",
    "Os Trapalhões",
    "A Morte te dá Parabéns",
    "Avatar",
    "A Morte te dá Parabéns 2",
    "Us - Nós",
    "Corra!",
    "Homem-Aranha",
    "Homem-Aranha 2",
    "Homem-Aranha 3",
    "O Espetacular Homem-Aranha",
    "O Espetacular Homem-Aranha 2",
    "Homem-Aranha no Aranhaverso",
    "Homem-Aranha - De volta ao lar",
    "Homem-Aranha - Longe de Casa",
    "Vida de Inseto",
    "O Pequeno Stuart Little",
    "Formiguinhaz",
    "Frozen",
    "Viva - A Vida é uma Festa",
    "Valente",
    "Coração Valente",
    "Batman e Robin",
    "Superman - O Retorno",
    "O Homem de Aço",
    "Jovens Titans em Ação",
    "King-Kong",
    "Harry Potter e a Pedra Filosofal",
    "Harry Potter e a Câmara Secreta",
    "Harry Potter e os Prisioneiros de Askaban",
    "Harry Potter e o Cálice de Fogo",
    "Harry Potter e o Enigma do Principe",
    "Harry Potter e as Reliquias da Morte: Parte 1",
    "Jogos Vorazes",
    "Jogos Vorazes: Em chamas",
    "Jogos Vorazes: A Esperança - Parte 1",
    "Jogos Vorazes: A Esperança - O Final",
    "Eu Sou o Numero 4",
    "Moana: Um Mar de Aventuras",
    "Divergente",
    "Velozes e Furiosos",
    "+ Velozes e + Furiosos",
    "Velozes e Furiosos - Desafio em Tóquio",
    "Velozes e Furiosos 4",
    "Velozes e Furiosos 5 - Operação Rio",
    "Velozes e Furiosos 6",
    "Velozes e Furiosos 7",
    "Velozes e Furiosos 8",
    "Assassin's Creed",
    "Guerra Mundial Z",
    "Zumbilandia",
    "Invocação do Mal",
    "Invocação do Mal 2",
    "A Freira",
    "Annabelle",
    "Annabelle 2",
    "A Maldição da Chorona",
    "Aquaman",
    "Esquadrão Suicida",
    "Coringa",
    "Venom",
    "Thor",
    "Thor: O Mundo Sobrio",
    "X-Men - O Filme",
    "X-Men 2",
    "X-Men 3: O Confronto Final",
    "X-Men: Primeira Classe",
    "X-Men: Dias de um Futuro Esquecido",
    "X-Men: Apocalipse",
    "X-Men: Fênix Negr",
    "X-Men: Origens Wolverine",
    "Wolverine: Imortal",
    "Maze Runner: Correr ou Morrer",
    "Maze Runner: Prova de Fogo",
    "Maze Runner: A Cura Mortal",
    "A Múmia",
    "O Exorcista",
    "O Exorcismo de Emily Rose",
    "O Ultimo Exorcismo",
    "O Ultimo Mestre do Ar",
    "Fragmentado",
    "Corpo Fechado",
    "Vidro",
    "O Sexto Sentido",
    "Imortais",
    "Passageiros",
    "Branca de Neve e os Sete Anões",
    "Pinóquio",
    "Fantasia",
    "Dumbo",
    "Bambi",
    "Alô Amigos",
    "Você já foi à Bahia?",
    "Música, Maestro",
    "Como é Bom se Divertir",
    "Tempo de Melodia",
    "Cinderela",
    "Alice no País das Maravilhas",
    "Peter Pan",
    "A Dama e o Vagabundo",
    "A Bela Adormecida",
    "101 Dálmatas",
    "Mogli: O Menino Lobo",
    "Aristogatas",
    "Robin Hood",
    "As Aventuras do Ursinho Pooh",
    "O Cão e a Raposa",
    "O Caldeirão Mágico",
    "Oliver e sua Turma",
    "A Pequena Sereia",
    "A Bela e a Fera",
    "Aladdin",
    "Pocahontas",
    "O Corcunda de Notre Dame",
    "Hécules",
    "Mulan",
    "Tarzan",
    "Fantasia 2000",
    "A Nova Onda do Imperador",
    "Atlantis: O Reino Perdido",
    "Lilo & Stitch",
    "Planeta Tesouro",
    "Irmão Urso",
    "Nem que a Vaca Tussa",
    "O Galinho Chicken Little",
    "A Família do Futuro",
    "Bolt: O Supercão",
    "A Princesa e o Sapo",
    "Enrolados",
    "Detona Ralph",
    "Frozen: Uma Aventura Congelante",
    "Operação Big Hero",
    "Zootopia: Essa Cidade é o Bicho",
    "WiFi-Ralph",
    "Meu Amigo, o Dragão",
    "A Volta ao Mundo em 80 Minutos",
    "Hollywood em Festa",
    "Pela Porta de Serviço",
    "DuckTales, o Filme: O Tesouro da Lâmpada Perdida",
    "Pateta: O Filme",
    "Doug: O Filme",
    "Tigrão: O Filme",
    "Pateta 2 - Radicalmente Pateta",
    "Hora do Recreio",
    "Peter Pan: De Volta à Terra do Nunca",
    "Mogli: O Menino Lobo 2",
    "Leitão: O Filme",
    "O Cãozinho Esperto",
    "Mickey, Donald e Pateta: Os Três Mosqueteiros",
    "Pooh e o Efalante",
    "Bambi 2",
    "Selvagem",
    "Tinker Bell: Uma Aventura no Mundo das Fadas",
    "Tinker Bell e o Tesouro Perdido",
    "Tinker Bell e o Resgate da Fada",
    "Tinker Bell: O Segredo das Fadas",
    "Aviões",
    "Tinker Bell: Fadas e Piratas",
    "Aviões 2: Heróis de Fogo ao Resgate",
    "Tinker Bell e o Monstro da Terra do Nunca",
    "Toy Story 2",
    "Monstros S.A.",
    "Procurando Nemo",
    "Os Incríveis",
    "Carros",
    "Ratatouille",
    "WALL-E",
    "Up: Altas Aventuras",
    "Carros 2",
    "Universidade Monstros",
    "O Bom Dinossauro",
    "Divertida Mente",
    "Procurando Dory",
    "Carros 3",
    "Os Incríveis 2",
    "O Estranho Mundo de Jack",
    "James e o Pêssego Gigante",
    "Frankenweenie",
    "Os Fantasmas de Scrooge",
    "Marte Precisa de Mães",
    "O Serviço de Entregas da Kiki",
    "Princesa Mononoke",
    "A Viagem de Chihiro",
    "O Reino dos Gatos",
    "O Castelo Animado",
    "Ponyo: Uma Amizade que Veio do Mar",
    "Contos de Terramar",
    "O Mundo dos Pequeninos",
    "A Torradeira Valente",
    "O Cavaleiro das Arábias",
    "A Torradeira Valente Vai a Marte",
    "A Tartaruga Manuelita",
    "A Torradeira Valente Vai à Escola",
    "Pokémon 4: Viajantes do Tempo",
    "Heróis Pokémon",
    "Valiant: Um Herói que Vale a Pena",
    "Turma da Mônica: Uma Aventura no Tempo",
    "Romeu: O Vira-Lata Atrapalhado",
    "Gnomeu e Julieta",
    "A Volta de Mary Poppins",
    "Kim Possible",
    "A Fuga das Galinhas",
    "Shrek",
    "Shrek 2",
    "O Espanta Tubarões",
    "Madagascar",
    "Os Sem Floresta",
    "Por Água Abaixo",
    "Shrek Terceiro",
    "Bee Movie",
    "Kung Fu Panda",
    "Madagascar: 2",
    "Monstros vs. Alienígenas",
    "Como Treinar o Seu Dragão",
    "Shrek para Sempre",
    "Megamente",
    "Kung Fu Panda 2",
    "O Gato de Botas",
    "Madagascar 3",
    "A Origem dos Guardiões",
    "Os Croods",
    "Turbo",
    "As Aventuras de Peabody e Sherman",
    "Como Treinar o Seu Dragão 2",
    "Os Pinguins de Madagascar",
    "Cada um na Sua Casa",
    "Kung Fu Panda 3",
    "Trolls",
    "O Poderoso Chefinho",
    "As Aventuras do Capitão Cueca",
    "Como Treinar o Seu Dragão 3",
    "Alvin e os Esquilos",
    "A Era do Gelo",
    "Duro de Matar",
    "Esqueceram de Mim",
    "Clube da Luta",
    "Rio",
    "Rio 2",
    "Titanic",
    "Deadpool",
    "Deadpool 2",
    "Uma Noite no Museu",
    "Quarteto Fantástico e o Surfista Prateado",
    "Independece Day",
    "Kigsman: Serviço Secreto",
    "Alien vs Predador",
    "A Era do Gelo 2: O Degelo",
    "O Predador",
    "Pequenos Invasores",
    "Dr. Dolittle",
    "Atrás das Linhas Inimigas",
    "Tora! Tora! Tora!",
    "Uma Secretária do Futuro",
    "Elektra",
    "Náufrago",
    "Demolidor - O Homem sem Medo",
    "Perdido em Marte",
    "A Culpa é das Estrelas",
    "O Regresso",
    "O Diabo Veste Prada",
    "Alien - o Oitavo Passageiro",
    "Um sonho de Liberdade",
    "O Poderoso Chefão",
    "O Poderoso Chefão II",
    "Batman - O Cavaleiro das Trevas",
    "12 Homens e uma Sentença",
    "A Lista de Schindler",
    "Pulp Fiction: Tempo de Violência",
    "O Senhor dos Anéis: O Retorno do Rei",
    "Três homens em Conflito",
    "O Senhor dos Anéis: A Sociedade do Anel",
    "Forrest Gump: O Contador de Histórias",
    "Star Wars: Episódio V - O Império Contra-Ataca",
    "A Origem",
    "O Senhor dos Anéis: As Duas Torres",
    "Um Estranho no Ninho",
    "Os Bons Companheiros",
    "Matrix",
    "Os Sete Samurais",
    "Cidade de Deus",
    "Seven: Os Sete Crimes Capitais",
    "O Silêncio dos Inocentes",
    "A Felicidade Não se Compra",
    "A Vida é Bela",
    "O Profissional",
    "O Resgate do Soldado Ryan",
    "A Outra História Americana",
    "Era uma Vez no Oeste",
    "Interestelar",
    "À Espera de um Milagre",
    "Psicose",
    "Casablanca",
    "Luzes da Cidade",
    "Intocáveis",
    "Os Tempos Modernos",
    "O Pianista",
    "Indiana Jones e Os Caçadores da Arca Perdida",
    "Os Infiltrados",
    "Janela Indiscreta",
    "O Exterminador do Futuro 2: O Julgamento Final",
    "De Volta para o Futuro",
    "Whiplash: Em Busca da Perfeição",
    "Gladiador",
    "O Grande Truque",
    "O Rei Leão",
    "Amnésia",
    "Apocalypse Now",
    "O Grande Ditador",
    "Crepúsculo dos Deuses",
    "Cinema Paradiso",
    "Dr. Fantástico",
    "A Vida dos Outros",
    "O Túmulo dos Vagalumes",
    "Glória Feita de Sangue",
    "Django Livre",
    "O Iluminado",
    "Beleza Americana",
    "Blade Runner 2049",
    "Batman: O Cavaleiro das Trevas Ressurge",
    "Oldboy",
    "Aliens, O Resgate",
    "Testemunha de Acusação",
    "Era Uma Vez na América",
    "O barco: Inferno no Mar",
    "Dangal",
    "O Cidadão Kane",
    "Um Corpo que Cai",
    "Intriga Internacional",
    "Star Wars: Episódio VI - O Retorno de Jedi",
    "Cães de Aluguel",
    "M, O Vampiro de Dusseldorf",
    "Réquiem Para um Sonho",
    "Como Estrelas na Terra",
    "O Fabuloso Destino de Amélie Poulain",
    "Kimi no na wa.",
    "Laranja Mecânica",
    "Lawrence da Arábia",
    "Amadeus",
    "Pacto de Sangue",
    "Brilho Eterno de uma Mente Sem Lembranças",
    "Taxi Driver",
    "O Sol é Para Todos",
    "Nascido para Matar",
    "2001: Uma Odisseia no Espaço",
    "Cantando na Chuva",
    "Toy Story",
    "3 Idiots",
    "Golpe de Mestre",
    "Toy Story 3",
    "Bastardos Inglórios",
    "Ladrões de Bicicletas",
    "O Garoto",
    "Dunkirk",
    "Monty Python em Busca do Cálice Sagrado",
    "Gênio Indomável",
    "A Caça",
    "Por Uns Dólares a Mais",
    "Los Angeles: Cidade Proibida",
    "Scarface",
    "Se Meu Apartamento Falasse",
    "Metrópolis",
    "A Separação",
    "Rashomon",
    "Indiana Jones e a Última Cruzada",
    "A Malvada",
    "Yojimbo - O Guarda-Costas",
    "Meu Pai e Meu Filho",
    "Batman Begins",
    "Quanto Mais Quente Melhor",
    "O Tesouro da Sierra Madre",
    "Os Imperdoáveis",
    "A Queda! As Últimas Horas de Hitler",
    "Touro Indomável",
    "Fogo Contra Fogo",
    "Filhos do Paraíso",
    "Fugindo do Inferno",
    "Viver",
    "Chinatown",
    "O Labirinto do Fauno",
    "Meu Amigo Totoro",
    "Incêndios",
    "Ran",
    "Julgamento em Nuremberg",
    "Em Busca do Ouro",
    "O Segredo dos seus Olhos",
    "Sindicato de Ladrões",
    "A Ponte do Rio Kwai",
    "O Sétimo Selo",
    "O Quarto de Jack",
    "Jogos, Trapaças e Dois Canos Fumegantes",
    "A Mulher Faz o Homem",
    "Uma Mente Brilhante",
    "Cassino",
    "Blade Runner, o Caçador de Androides",
    "O Homem Elefante",
    "V de Vingança",
    "O Lobo de Wall Street",
    "General",
    "Guerreiro",
    "Disque M para Matar",
    "Trainspotting - Sem limites",
    "Gran Torino",
    "...E o Vento Levou",
    "Aurora",
    "O Franco Atirador",
    "Fargo - Uma Coméedia de erros",
    "O Enigma de Outro Mundo",
    "Andrey Rublev",
    "Onde os Fracos Não Têm Vez",
    "O Grande Lebowski",
    "O Bandido",
    "Era uma Vez em Tóquio",
    "Sangue Negro",
    "Rebeldia Indomável",
    "Vá e Veja",
    "Rebecca, A Mulher Inesquecível",
    "Até o Último Homem",
    "Kill Bill: Volume 1",
    "O Martírio de Joana D'Arc",
    "Mary e Max: Uma Amizade Diferente",
    "Garota Exemplar",
    "Ilha do Medo",
    "La La Land: Cantando Emoções",
    "Na Natureza Selvagem",
    "Monty Python: A Vida de Brian",
    "Aconteceu Naquela Noite",
    "Relatos Selvagens",
    "Logan",
    "Platoon",
    "O Salário do Medo",
    "Hotel Ruanda",
    "Rede de Intrigas",
    "Em Nome do Pai",
    "Rush: No Limite da Emoção",
    "Conta Comigo",
    "A Wednesday",
    "Thor: Ragnarok",
    "Quando Duas Mulheres Pecam",
    "Ben-Hur",
    "O Grande Hotel Budapeste",
    "Os Incompreendidos",
    "Memórias de um Assassino",
    "12 Anos de Escravidão",
    "Mad Max: Estrada da Fúria",
    "Menina de Ouro",
    "Spotlight: Segredos Revelados",
    "Stalker",
    "O Show de Truman",
    "Amores Brutos",
    "Butch Cassidy",
    "Sempre ao Seu Lado",
    "Nausicaä do Vale do Vento",
    "A Princesa Prometida",
    "Antes do Amanhecer",
    "Relíquia Macabra (O Falcão Maltês)",
    "Lua de Papel",
    "Noites de Cabíria",
    "Os Suspeitos",
    "Harry Potter e as Relíquias da Morte: Parte 2",
    "Vinhas da Ira",
    "Rocky: Um Lutador",
    "Prenda-me Se For Capaz",
    "As Diabólicas",
    "A Marca da Maldade",
    "Gandhi",
    "Barry Lyndon",
    "Noivo Neurótico, Noiva Nervosa",
    "O Exterminador do Futuro",
    "Star Wars: Episódio VII: O Despertar da Força",
    "O Ultimato Bourne",
    "O Mágico de Oz",
    "Feitiço do Tempo",
    "O Ódio",
    "Tubarão",
    "Os Melhores Anos de Nossas Vidas",
    "Os 12 Macacos",
    "Conflitos Internos",
    "Amor à Flor da Pele",
    "Paris, Texas",
    "Histórias Cruzadas",
    "Sociedade dos Poetas Mortos",
    "A Criada",
    "A Batalha de Argel",
    "Piratas do Caribe: A Maldição do Pérola Negra",
    "Gangs of Wasseypur",
    "Um Dia de Cão",
    "O Dragão Relutante",
    "Vitória Através do Poder Aéreo",
    "Alô, amigos",
    "Música, Maestro!",
    "A Canção do Sul",
    "Meu Querido Carneirinho",
    "As Aventuras de Ichabod e Sr. Sapo",
    "A Ilha do Tesouro",
    "Robin Hood, o Justiceiro",
    "Entre a Espada e a Rosa",
    "20.000 Léguas Submarinas",
    "Têmpera de bravos",
    "Audácia de um rebelde",
    "Meu Querido Companheiro",
    "A lenda dos anões mágicos",
    "Felpudo, o Cão Feiticeiro",
    "O Mundo Fabuloso do Circo",
    "A Espada de um Bravo",
    "Pollyanna",
    "O Incrível Zorro",
    "Os Dez Ousados",
    "A Cidadela dos Robinson",
    "O Fantástico Super-Homem",
    "Operação Cupido",
    "Nikki, O Cão Selvagem do Norte",
    "Meu Leal Companheiro",
    "O Mundo Encantado dos Brinquedos",
    "Bon-Voyage, Enfim Paris",
    "O Campeão",
    "Quase Anjos",
    "A Montanha do Lobo Sanguinário",
    "As Grandes Aventuras do Capitão Grant",
    "Na trilha dos Apaches",
    "Doce Verão dos Meus Sonhos",
    "A Incrível Jornada",
    "A Espada Era a Lei",
    "O Segredo das Esmeraldas Negras",
    "Mary Poppins",
    "Em busca da aventura",
    "Aquele Gato Danado",
    "Nunca é tarde para amar",
    "Eu Acredito em Gnomos",
    "Mogli - O Menino Lobo",
    "Se meu fusca falasse",
    "O Computador de Têni",
    "Percy Jackson e o Ladrão de Raios",
    "Robocop",
    "Minority Report",
    "Os Simpsons",
    "Arquivo X",
    "Marley e Eu",
    "A Paixão de Cristo",
    "Cruzada",
    "Guerra é Guerr",
    "Victor Freinkeinstein",
    "Birdman",
    "Bird Box",
    "Eu, Robô",
    "O Fada do Dente",
    "500 Dias com Ela",
    "Garota Infernal",
    "Transformers",
    "Esquadrão Classe A",
    "DPA - Detetives do Prédio Azul",
    "Se Minha Cama Voasse",
    "Dinheiro, Poder e Bananas",
    "A Pata de um Milhão de Dólares",
    "O Comedor de Biscoito",
    "Napoleão e Samantha",
    "Os Invencíveis Invisíveis",
    "Aventuras Na Neve",
    "Superpai",
    "O Maior Atleta do Mundo",
    "O pequeno índio",
    "As Novas Aventuras do Fusca",
    "Um Cowboy no Havaí",
    "A Ilha do Topo do Mundo",
    "O Homem Mais Forte do Mundo",
    "A Montanha Enfeitiçada",
    "Gang em Apuros",
    "Está Faltando um de Nossos Dinossauros",
    "Se Eu Fosse a Minha Mãe",
    "Gus, uma Mula Fora de Série",
    "Garotos Travessos",
    "Felpudo, o Cão promotor",
    "O Fusca Enamorado",
    "Candleshoe: O Segredo da Mansão",
    "Chumbo Quente e Pé Frio",
    "Perigo na Montanha Enfeitiçada",
    "O Gato que Veio do Espaço",
    "Um Astronauta Na Corte Do Rei Arthur",
    "A Gangue da Tortinha de Maçã Ataca Novamente",
    "O Buraco Negro",
    "A Última Cruzada Do Fusca",
    "Condorman - O Homem Pássaro",
    "Mistério no Bosque",
    "Se Viver, Mande um Postal",
    "O Mundo Fantástico de Oz",
    "Viagem Clandestina",
    "Um Natal Mágico",
    "O Navegador do Espaço",
    "Benji-Um Cão desafia a Selva",
    "Caninos Brancos",
    "Mergulho em uma Paixão",
    "The Rocketeer",
    "Extra! Extra!",
    "Querida, Estiquei o Bebê",
    "Nós Somos os Campeões",
    "Os Três Mosqueteiros",
    "Jamaica Abaixo de Zero",
    "Iron Will - O Grande Desafio",
    "Cheque em Branco",
    "Nós Somos os Campeões 2",
    "Caninos Brancos 2 - A Lenda do Lobo Branco",
    "Pesos Pesados",
    "Operação Dumbo",
    "Um garoto na corte do Rei Artur",
    "Pisando na bola",
    "A incrível jornada II: Perdidos em São Francisco",
    "Meu Filho das Selvas",
    "Flubber - Uma Invenção Desmiolada",
    "Mr. Magoo",
    "Aurora Boreal",
    "Um Amor de Múmia",
    "Os Irmãos Id & Ota",
    "Poderoso Joe",
    "Minha Vida com Lucky",
    "Brink!",
    "Halloweentown",
    "Uma História Real",
    "Zenon: A Garota do Século 21",
    "A Caixa de Pandora",
    "O 13º Aniversário",
    "A Casa Inteligente",
    "Johnny Tsunami: O Surfista da Neve",
    "Gênio: Desafiando a Gravidade e o Amor",
    "Meu Amigo Bicho Papão",
    "Um jeito Especial com Cavalos",
    "Meu Namorado é um Zumbi",
    "Zumbilândia 2",
    "Exterminio",
    "Exterminio 2",
    "Exterminio 3",
    "Fim dos Tempos",
    "Gente Grande",
    "Gente Grande 2",
    "Aperte os Cintos que o Piloto Sumiu",
    "A Casa Monstro",
    "Ultraje",
    "Gangues de Brooklyn",
    "Crocodilo Dundee",
    "Twister",
    "Quebrando Regras",
    "A Intrometida",
    "Linha de Passe",
    "A Inocência",
    "A Lenda do Tesouro Perdido",
    "Esqueceram de Mim 2",
    "Esqueceram de Mim 3",
    "Esqueceram de Mim 4",
    "O Homem do Ano",
    "Mutum",
    "Reino dos Assassinos",
    "Operação Rogue",
    "Asterix nos Jogos Olimpicos",
    "A Profecia",
    "Roubo a Máfia",
    "Pequenos Milagres",
    "Planeta Terror",
    "A Volta dos Bravos",
    "Corações Sujos",
    "O Cachorro",
    "A Noiva-Cadáver",
    "O Equilibrista",
    "Brigada 49",
    "Caro Diário",
    "Antes do Pôr-do-Sol",
    "Pecados Íntimos",
    "Caça às Bruxas",
    "Julieta",
    "Lassie",
    "JCVD",
    "Mother - A Busca pela Verdade",
    "Segredos de um Crime",
    "Close",
    "Feitiço Negro",
    "Efeito Borboleta",
    "Inversão",
    "O Conto dos Contos",
    "Segurança Nacional",
    "Alien vs. Predador 2",
    "Caçadores de Mentes",
    "O Passado",
    "Ouro Negro",
    "Uma Noite de Crime",
    "Uma Noite de Crime: Anarquia",
    "O Amuleto",
    "Os Belos Dias",
    "Vício e Beleza",
    "Vozes do Alpem",
    "A Outra Face",
    "Plano de Vingança",
    "Sansão",
    "Encurralados",
    "Olhos de Gato",
    "Reino de Fogo",
    "Operação Fronteira",
    "Vovó... Zona",
    "Norbit",
    "Jean Charles",
    "Voo 7500",
    "Cimarron",
    "Premonição",
    "Premonição 2",
    "Premonição 3",
    "Premonição 4",
    "O Lago",
    "Cargo",
    "O Homem que Matou John Wayne",
    "Garantia de Morte",
    "Do Inferno",
    "Minha Vida com Lebarace",
    "Sinfonia da Necrópole",
    "O Corvo",
    "Tammy",
    "À Francesa",
    "Penitências",
    "O Primeiro que Disse",
    "Anna e o Rei",
    "Macunaíma",
    "Bones",
    "Shoah",
    "Meteora",
    "Ela dança, Eu danço",
    "Chaplin",
    "A Luta de um Campeão",
    "Premonições",
    "Minha Adoráveis Ex-Namoradas",
    "Submarino",
    "Já Não Me Sinto Em Casa Nesse Mundo",
    "Senhor do Crime",
    "Todos Dizem Eu Te Amo",
    "Possessão",
    "Beleza Oculta",
    "3 Efes",
    "A Banda",
    "Paulina",
    "Endiabrado",
    "Suando Frio",
    "A Noiva Perfeita",
    "Vale da Luta",
    "Ellie Parker",
    "A Cura",
    "Gravidade",
    "A Vida Secreta das Palavras",
    "Atividade Paranormal",
    "Atividade Paranormal 2",
    "Atividade Paranormal 3",
    "Atividade Paranormal 4",
    "A Escolha",
    "Noivas",
    "Fonte da Juventude",
    "O Bebê de Rosemary",
    "Filmefobia",
    "Cercar e Destruir",
    "Xuxa e os Duendes",
    "Tudo que Quero",
    "Quincas Berro d'Água",
    "Paulo, O Apostolo de Cristo",
    "Na Quebrada",
    "As Tartarugas Ninja",
    "Kóblic",
    "Feliz Natal",
    "Um Tiro na Noite",
    "A Entranha Perfeita",
    "Coisas do Coração",
    "Sexo por Compaixão",
    "A Ovelha Negra",
    "Nada a Esconder",
    "14 Bis",
    "Orgulho e Preconceito e Zumbis",
    "O Fim do Mundo, Enfim",
    "Luz Apagada",
    "O Homem que Fazia Chover",
    "Operação Red Sparrow",
    "Bratz - O Filme",
    "Para se Divertir, Ligue...",
    "Virgínia",
    "Cenas de Crimes",
    "A Hora do Espanto",
    "A Pele de Vênus",
    "Eu Fiko Loko",
    "A Tentação",
    "Como Você me Vê?",
    "Terras",
    "Jogo de Cena",
    "Contaminação",
    "Solo",
    "Um Dia de Fúria",
    "Luto como Mãe",
    "Henry",
    "Portal dos Guerreiros",
    "Força Policial",
    "O Homem Urso",
    "Tamara",
    "Ciborgue",
    "Reis e Rainha",
    "Timemaster",
    "Minha Vida em Marte",
    "Bohemian Rhapsody",
    "Nasce uma Estrela",
    "Megaturabarão",
    "Jurassic World: Reino Ameaçado",
    "Bumblebee",
    "Alita: Anjo de Combate",
    "Green Book - O Guia",
    "O Protetor 2",
    "Mamma Mia: Lá Vamos Nós de Novo",
    "Halloween",
    "Creed",
    "Creed II",
    "Robin Hood - A Origem",
    "Dragon Ball Super: Broly",
    "Infiltrado na Klan",
    "Pé Pequeno",
    "Buscando...",
    "A Caminho de Casa",
    "Oito Mulheres e Um Segredo",
    "Christopher Robin",
    "Alfa",
    "O Primeiro Homem",
    "Vice",
    "Arranha-Céu - Coragem Sem Limite",
    "Minios",
    "A Favorita",
    "Vermelho Brasil",
    "Goosebumps",
    "Star Wars VIII: Os Últimos Jedi",
    "Star Wars IV: Uma Nova Esperança",
    "Star Wars: A Ameaça Fantasma",
    "Star Wars II: A Guerra dos Clones",
    "Star Wars III: A Vingança de Sith"
    "Jumanji: Bem-Vindo A Selva",
    "A Fantástica Fábrica de Chocolate",
    "Rogue One: Uma Aventura Star Wars",
    "Alice Através do Espelho",
    "Pixels",
    "Scooby-Doo",
    "A Lagoa Azul",
    "As Panteras",
    "Aprendiz de Feiticeiro",
    "Superman - O Filme",
    "Desventuras em Série",
    "Viagem ao Centro da Terra - O Filme",
    "Ponte Para Terabítia",
    "Fúria de Titãs",
    "A Lenda do Zorro",
    "Zathura - Uma Aventura Espacial",
    "Space Jam - O Jogo do Século",
    "Herbie: Meu Fusca Turbinado",
    "Os Goonies",
    "O Caçador e a Rainha do Gelo",
    "Free Willy",
    "Mogli: Entre Dois Mundos",
    "Warcraft - O Primeiro Encontro de Dois Mundos",
    "Viagem 2: A Ilha Misteriosa",
    "Cidades de Papel",
    "Deuses do Egito",
    "De Volta à Lagoa Azul",
    "John Carter: Entre Dois Mundos",
    "Treze Homens e Um Novo Segredo",
    "A Bússola de Ouro",
    "Hulk",
    "O Último Caçador de Bruxas",
    "Valerian e a Cidade dos Mil Planetas",
    "As Aventuras de Sharkboy e Lavagirl",
    "O Espaço entre Nós",
    "Força-G",
    "Jack: O Caçador de Gigantes",
    "Dança com Lobos",
    "Mortal Kombat",
    "Austrália",
    "Menino Maluquinho - O Filme",
    "Pequenos Espiões 2 - A Ilha dos Sonhos Perdidos",
    "Mar em Fúria",
    "10.000 A.C.",
    "Meu Monstro de Estimação",
    "Pequenos Ivasores",
    "Vira-Lata",
    "Solomon Kane - O Caçador de Demônios",
    "Arthur e os Minimoys",
    "Aeon Flux",
    "O Gato",
    "Marmaduke",
    "Deu Zebra!",
    "Benji",
    "Beethoven",
    "O Senhor dos Ladrões",
    "Max Steel",
    "Dragonball - Evolution",
    "Estrada Alucinante",
    "Moby Dick",
    "Os Xeretas",
    "O Saci",
    "Fome de Poder",
    "Um Homem Entre Gigantes",
    "Steve Jobs",
    "Tudo Por Um Pop Star",
    "Os Farofeiros",
    "De Repente Uma Família",
    "De Repente 30",
    "Um Quase Dupla",
    "Fala Sério, Mãe!",
    "Todo Poderoso",
    "Click",
    "O Máskara",
    "Amizade Colorida",
    "Se Beber, Não Case!",
    "O Diário da Princesa",
    "Viagem à Lua",
    "O grande roubo do trem",
    "O nascimento de uma nação",
    "Os vampiros",
    "Intolerância",
    "O gabinete do Dr. Caligari",
    "Lírio partido",
    "Inocente pecadora",
    "Within our gates",
    "A carruagem fantasma",
    "Órfãs da tempestade",
    "A sorridente madame Beudet",
    "Dr. Mabuse, o jogador",
    "Nanook, o esquimó",
    "Nosferatu",
    "Häxan - A Feitiçaria através dos Tempos",
    "Esposas ingênuas",
    "Nossa hospitalidade",
    "A roda",
    "O ladrão de Bagdá",
    "A greve",
    "Ouro e maldição",
    "Bancando o Águia",
    "A última gargalhada",
    "Sete oportunidades",
    "O fantasma da ópera",
    "O encouraçado Potemkin",
    "O grande desfile",
    "A General",
    "O monstro do circo",
    "Outubro",
    "O cantor de jazz",
    "Napoleão",
    "O caçula",
    "A turba",
    "Docas de Nova York",
    "Um cão andaluz",
    "Marinheiro de encomenda",
    "Tempestade sobre a Ásia",
    "Chantagem e confissão",
    "Um homem com uma câmera",
    "O anjo azul",
    "A Idade do Ouro",
    "Terra",
    "Alma no lodo",
    "Sem novidade no front",
    "A nós a liberdade",
    "O milhão",
    "Tabu",
    "Limite",
    "Drácula",
    "Frankenstein",
    "Inimigo público nº1",
    "M - o vampiro de Dusseldorf",
    "A cadela",
    "O vampiro",
    "Ama-me esta noite",
    "Boudu salvo das águas",
    "O fugitivo",
    "Ladrão de alcova",
    "Scarface - a vergonha de uma nação",
    "O Expresso de Shanghai",
    "Monstros",
    "Eu e minha pequena",
    "Zero em comportamento",
    "Rua 42",
    "Belezas em revista",
    "Caçadoras de ouro",
    "Um loira para três",
    "O diabo a quatro",
    "Rainha Cristina",
    "Terra sem pão",
    "King Kong",
    "O último chá do General Yen",
    "Os filhos do deserto",
    "It's a gift",
    "O triunfo da vontade",
    "O atalante",
    "O gato preto",
    "Juiz Priest",
    "A ceia dos acusados",
    "Capitão Blood",
    "O grande motim",
    "Uma noite na ópera",
    "Os 39 degraus",
    "A noiva de Frankenstein",
    "O picolino",
    "Um dia no campo",
    "Tempos modernos",
    "Ritmo louco",
    "Irene, a teimosa",
    "O galante Mr. Deeds",
    "A dama das camélias",
    "O marido era o culpado",
    "Fogo de Outono",
    "Daqui a cem anos",
    "O romance de um trapaceiro",
    "Marujo intrépido",
    "Canção da noite",
    "A grande ilusão",
    "Stella Dallas, mãe redentora",
    "A vida de Émile Zola",
    "A cruz dos anos",
    "Cupido é moleque teimoso",
    "O demônio da Argélia",
    "Jezebel",
    "As aventuras de Robin Hood",
    "Anjos de cara suja",
    "Olympia",
    "A mulher do padeiro",
    "Levada da breca",
    "No tempo das diligências",
    "Crisântemos tardios",
    "Sangue de artista",
    "Atire a primeira pedra",
    "Paraíso infernal",
    "E o vento levou",
    "Trágico amanhecer",
    "Gunga Din",
    "Ninotchka",
    "A regra do jogo",
    "O morro dos ventos uivantes",
    "Jejum de amor",
    "Rebecca - a mulher inesquecível",
    "Núpcias de escândalo",
    "As vinhas da ira",
    "A vida é uma dança",
    "Tempestades d'alma",
    "O guarda",
    "Cidadão Kane",
    "As três noites de Eva",
    "O lobisomem",
    "Relíquia macabra",
    "Sargento York",
    "Seu último refúgio",
    "Contrastes humanos",
    "Como era verde o meu vale",
    "Mulher de verdade",
    "A estranha passageira",
    "Ser ou não ser",
    "Sangue de pantera",
    "Soberba",
    "A canção da vitória",
    "Meshes of the afternoon",
    "Fires were started",
    "The man in grey",
    "Coronel Blimp - vida e morte",
    "A morta viva",
    "A sétima vítima",
    "Consciências mortas",
    "A sombra de uma dúvida",
    "Obsessão",
    "Agora seremos felizes",
    "Uma aventura na Martinica",
    "Laura",
    "À meia luz",
    "Henrique V",
    "Ivan, o terrível - Parte I",
    "Ivan, o terrível - Parte II",
    "Até a vista, querida",
    "A batalha de San Pietro",
    "Quando fala o coração",
    "Alma em suplício",
    "O boulevard do crime",
    "Roma, cidade aberta",
    "Farrapo humano",
    "Curva do destino",
    "Sei onde fica o paraíso",
    "Desencanto",
    "Paisà",
    "O destino bate à sua porta",
    "A paixão dos fortes",
    "O estranho",
    "À beira do abismo",
    "Os assassinos",
    "Neste mundo e no outro",
    "Grandes esperanças",
    "Interlúdio",
    "Narciso negro",
    "Gilda",
    "Monsieur Verdoux",
    "Fuga do passado",
    "O fantasma apaixonado",
    "O condenado",
    "Ladrões de bicicleta",
    "Carta de uma desconhecida",
    "O segredo da porta fechada",
    "Força do Mal",
    "Primavera numa cidade pequena",
    "Rio Vermelho",
    "Festim diabólico",
    "A cova da serpente",
    "A dama de Shanghai",
    "O valente treme-treme",
    "Os sapatinhos vermelhos",
    "O tesouro de Sierra Madre",
    "A História de Louisiana",
    "Tarde demais",
    "As oito vítimas",
    "Mortalmente perigosa",
    "A costela de Adão",
    "Alegrias à granel",
    "Fúria sanguinária",
    "Na teia do destino",
    "O terceiro homem",
    "Um dia em Nova York",
    "Orfeu",
    "O segredo das jóias",
    "Winchester ’73",
    "Rio Grande",
    "Os esquecidos",
    "No silêncio da noite",
    "A montanha dos sete abutres",
    "Uma rua chamada pecado",
    "Pacto sinistro",
    "O mistério da torre",
    "Os amores de Pandora",
    "Uma aventura na África",
    "Diário de um Padre",
    "Sinfonia de Paris",
    "Um lugar ao sol",
    "O dia em que a Terra parou",
    "Depois do vendaval",
    "Brinquedo proibido",
    "Alma em pânico",
    "Ikiru - Viver",
    "Europa 51",
    "Assim estava escrito",
    "O rio da aventura",
    "Matar ou morrer",
    "Umberto D",
    "A carruagem de ouro",
    "O bígamo",
    "A roda da fortuna",
    "Desejos proibidos",
    "A um passo da eternidade",
    "A Princesa e o plebeu",
    "O preço de um homem",
    "Anjo do Mal",
    "Os homens preferem as loiras",
    "Os corruptos",
    "As férias do senhor Hulot",
    "Viagem à Itália",
    "Contos da lua vaga",
    "Os brutos também amam",
    "O diabo riu por último",
    "Johnny Guitar",
    "Sete noivas para sete irmãos",
    "A revolução dos bichos",
    "A Condessa descalça",
    "A estrada da vida",
    "Sedução da carne",
    "Homens indomáveis",
    "Carmen Jones",
    "O Intendente Sansho",
    "O sal da terra",
    "Artistas e modelos",
    "Eles e elas",
    "A canção da estrada",
    "Conspiração do silêncio",
    "Os mestres loucos",
    "Hill 24 doesn't answer",
    "Quinteto da morte",
    "Marty",
    "A palavra",
    "O jogador",
    "A morte num beijo",
    "Um certo Capitão Lockhart",
    "Juventude transviada",
    "Cidade do vício",
    "Sorrisos de uma noite de amor",
    "Noite e nevoeiro",
    "O mensageiro do diabo",
    "Lola Montès",
    "Planeta proibido",
    "A harpa da Birmânia",
    "Rastros de ódio",
    "O homem que não vendeu sua alma",
    "Um condenado à morte escapou",
    "Palavras ao vento",
    "O homem que sabia demais",
    "Assim caminha a humanidade",
    "Tudo que o céu permite",
    "Vampiros de almas",
    "O homem errado",
    "Delírio de loucura",
    "Alta sociedade",
    "Os dez mandamentos",
    "Tarde demais para esquecer",
    "Morangos silvestres",
    "As noites de Cabíria",
    "Trono manchado de sangue",
    "O incrível homem que encolheu",
    "O invencível",
    "Sem Lei e sem alma",
    "Mãe Índia",
    "Quando voam as cegonhas",
    "A embriaguez do sucesso",
    "O homem do Oeste",
    "Cairo station",
    "Gigi",
    "Acorrentados",
    "Cinzas e diamantes",
    "O vampiro da noite",
    "Meu tio",
    "A sala de música",
    "Anatomia de um crime",
    "Os olhos sem rosto",
    "O homem que luta só",
    "Orfeu negro",
    "Sombras",
    "O mundo de Apu",
    "Acossado",
    "Batedor de carteiras",
    "Hiroshima, meu amor",
    "Onde começa o inferno",
    "A um passo da liberdade",
    "Ervas flutuantes",
    "Rocco e seus irmãos",
    "A doce vida",
    "Tudo começou no sábado",
    "Atirem no pianista",
    "A aventura",
    "A adolescente",
    "The cloud-capped star",
    "A empregada",
    "A máscara do demônio",
    "A tortura do medo",
    "Spartacus",
    "Clamor do sexo",
    "O ano passado em Marienbad",
    "La Jetée",
    "A face oculta",
    "Lola",
    "Bonequinha de luxo",
    "A noite",
    "Jules e Jim - uma mulher para dois",
    "Viridiana",
    "O terror das mulheres",
    "Através de um espelho",
    "Crônica de um verão",
    "Desafio à corrupção",
    "Amor, sublime amor",
    "Mundo cão",
    "Cléo de 5 às 7",
    "Dog star man",
    "A rotina tem seu encanto",
    "O eclipse",
    "Sob o domínio do mal",
    "Lolita",
    "O pagador de promessas",
    "O homem que matou o facínora",
    "O que terá acontecido a Baby Jane?",
    "Viver a vida",
    "Heaven and Earth magic",
    "Os pássaros",
    "O professor aloprado",
    "Blonde Cobra",
    "The cool world",
    "8 1/2",
    "A passageira",
    "O desprezo",
    "O indomado",
    "Luz de inverno",
    "Criaturas flamejantes",
    "Paixões que alucinam",
    "O Leopardo",
    "Vidas secas",
    "Méditerranée",
    "The house is black",
    "Desafio ao além",
    "A vingança do ator",
    "O criado",
    "007 contra Goldfinger",
    "Scorpio rising",
    "Os guarda-chuvas do amor",
    "Marnie, confissões de uma ladra",
    "Minha bela dama",
    "A mulher de areia",
    "Os reis do iê iê iê",
    "O deserto vermelho",
    "Os cavalos de fogo",
    "Máscara mortal",
    "Antes da Revolução",
    "Gertrud",
    "O Evangelho segundo São Mateus",
    "Deus e o diabo na terra do sol",
    "Onibaba - a mulher demônio",
    "Vinyl",
    "A pequena loja da rua Principal",
    "Doutor Jivago",
    "The war game",
    "Tokyo Olympiad",
    "A hora e a vez de Augusto Matraga",
    "A noviça rebelde",
    "O manuscrito de Saragoça",
    "Alphaville",
    "Badaladas à meia-noite",
    "Repulsa ao sexo",
    "Julieta dos espíritos",
    "O demônio das onze horas",
    "Faster, Pussycat! Kill! Kill!",
    "Subarnarekha",
    "O homem da cabeça raspada",
    "Hold me while I'm naked",
    "Blow up - depois daquele beijo",
    "As pequenas margaridas",
    "O grande mestre beberrão",
    "O segundo rosto",
    "Quem tem medo de Virginia Woolf?",
    "Persona",
    "Masculino - Feminino",
    "A grande testemunha",
    "No calor da noite",
    "Duas ou três coisas que eu sei dela",
    "A primeira noite de um homem",
    "Tempo de diversão",
    "Report",
    "Hombre",
    "A bela da tarde",
    "Duas garotas românticas",
    "Weekend à francesa",
    "O Samurai",
    "À queima-roupa",
    "Wavelenght",
    "Bonnie e Clyde - uma rajada de balas",
    "Vermelhos e brancos",
    "Marketa Lazarova",
    "O baile dos bombeiros",
    "Terra em transe",
    "Trens estreitamente vigiados",
    "O espírito do mal",
    "A vaca",
    "Planeta dos macacos",
    "Faces",
    "If",
    "Memórias do subdesenvolvimento",
    "Primavera para Hitler",
    "David Holzman's diary",
    "O bandido da luz vermelha",
    "Vergonha",
    "A hora do Lobo",
    "Na mira da morte",
    "A noite dos mortos-vivos",
    "Minha noite com ela",
    "Lucia",
    "Hsia nu",
    "Butch Cassidy e Sundance Kid",
    "Perdidos na noite",
    "Satyricon",
    "Z",
    "O conformista",
    "Sem destino",
    "High School",
    "In the Year of the Pig",
    "Meu ódio será sua herança",
    "Andrei Rublev",
    "O açougueiro",
    "A cor da romã",
    "Kes",
    "Tristana, uma paixão mórbida",
    "Cada um vive como quer",
    "El Topo",
    "Woodstock - 3 dias de paz, amor e música",
    "Ato final",
    "A estratégia da aranha",
    "Pequeno grande homem",
    "Orelha",
    "Patton - rebelde ou herói",
    "M*A*S*H",
    "Performance",
    "Gimme shelter",
    "Zabriskie Point",
    "O pássaro das plumas de cristal",
    "O jardim dos Finzi-Contini",
    "Wanda",
    "W.R.: Mysteries of the organism",
    "A dor e a piedade",
    "Quando os homens são homens",
    "A longa caminhada",
    "Klute - O passado condena",
    "Ensina-me a viver",
    "Salmo vermelho",
    "Carter - o vingador",
    "Operação França",
    "Shaft",
    "Perseguidor implacável",
    "O sopro no coração",
    "Sweet Sweetback’s baadasssss song",
    "A última sessão de cinema",
    "Sob o domínio do medo",
    "Corrida sem fim",
    "O rapaz que partia corações",
    "Aguirre, a cólera dos deuses",
    "Cabaré",
    "O último tango em Paris",
    "O estranho sem nome",
    "Trama diabólica",
    "Amargo pesadelo",
    "Solaris",
    "Gritos e sussurros",
    "Cidade das ilusões",
    "O discreto charme da burguesia",
    "As lágrimas amargas de Petra Von Kant",
    "Frenesi",
    "Pink flamingos",
    "Superfly",
    "A mãe e a puta",
    "Terra de ninguém",
    "Loucuras de verão",
    "Papillon",
    "Operação dragão",
    "Caminhos perigosos",
    "O perigoso adeus",
    "O homem de palha",
    "A noite americana",
    "Inverno de sangue em Veneza",
    "Dorminhoco",
    "Serpico",
    "Louca paixão",
    "O espírito da colméia",
    "O planeta fantástico",
    "Amarcord",
    "Balada sangrenta",
    "Pat Garrett e Billy The Kid",
    "Dersu Uzala",
    "A conversação",
    "O massacre da serra elétrica",
    "O espelho",
    "Uma mulher sob influência",
    "O jovem Frankenstein",
    "Céline et Julie vont en bateau",
    "Banzé no Oeste",
    "O poderoso chefão - parte II",
    "O medo devora a alma",
    "Tragam-me a cabeça de Alfredo Garcia",
    "Jeanne Dielman",
    "The rocky horror picture show",
    "Deewaar",
    "Monthy P. em busca do cálice sagrado",
    "O direito do mais forte",
    "India song",
    "Piquenique na montanha misteriosa",
    "Manila in the claws of brightness",
    "Saló, os 120 dias de Sodoma",
    "Nashville",
    "Cria cuervos",
    "Os atores ambulantes",
    "A morte de um bookmaker chinês",
    "Carrie, a estranha",
    "Josey Wales, o fora-da-lei",
    "Dona Flor e seus dois maridos",
    "Todos os homens do presidente",
    "Rocky, um lutador",
    "Voskhozhdeniye",
    "O império dos sentidos",
    "1900",
    "O homem que caiu na Terra",
    "Star wars",
    "Contatos imediatos de terceiro grau",
    "A última onda",
    "Last chants for a slow dance",
    "Stroszek",
    "O homem de mármore",
    "Os embalos de sábado à noite",
    "Killer of sheep",
    "Eraserhead",
    "Ceddo",
    "O amigo americano",
    "Quadrilha de sádicos",
    "Soldado de laranja",
    "Suspiria",
    "O canto de Jimmie Blacksmith",
    "Os cinco venenos",
    "A árvore dos tamancos",
    "Grease - nos tempos da brilhantina",
    "Cinzas do Paraíso",
    "Despertar dos mortos",
    "Shaolin master killer",
    "Queimando tudo",
    "Halloween - a noite do terror",
    "O casamento de Maria Braun",
    "Real life",
    "Bye bye Brasil",
    "As quatro irmãs",
    "O vencedor",
    "O tambor",
    "All that jazz - o show deve continuar",
    "Muito além do jardim",
    "Kramer vs. Kramer",
    "A vida de Brian",
    "Apocalipse now",
    "O panaca",
    "Muppets - o filme",
    "Manhattan",
    "Mad Max",
    "Nosferatu - O vampiro da noite",
    "Gente como a gente",
    "Atlantic city",
    "O último metrô",
    "Star wars V - o Império contra-ataca",
    "Agonia e glória",
    "Loulou",
    "Apertem os cintos, ...",
    "Os caçadores da Arca perdida",
    "O barco, inferno no mar",
    "Gallipoli",
    "Carruagens de fogo",
    "Corpos ardentes",
    "Reds",
    "Um lobisomem americano em Londres",
    "Pixote",
    "Três irmãos",
    "O homem de ferro",
    "Too early, too late",
    "Eles não usam black-tie",
    "Picardias estudantis",
    "E.T. , o extraterrestre",
    "O enigma do outro mundo",
    "Poltergeist - o fenômeno",
    "Blade Runner - o caçador de andróides",
    "A morte do demônio",
    "Tootsie",
    "Yol",
    "Quando os jovens se tornam adultos",
    "Fitzcarraldo",
    "A noite de São Lourenço",
    "Uma questão de silêncio",
    "Uma história de Natal",
    "El Norte",
    "Videodrome - a síndrome do vídeo",
    "Star wars VI - o retorno de Jedi",
    "O reencontro",
    "Sem sol",
    "O último combate",
    "O dinheiro",
    "Utu",
    "Laços de ternura",
    "O quarto homem",
    "O rei da comédia",
    "Os eleitos",
    "Koyaanisqatsi - Uma vida fora de equilíbrio",
    "A balada de Narayama",
    "A hora do pesadelo",
    "Spinal tap",
    "Um tira da pesada",
    "Cabra marcado para morrer",
    "Os caça-fantasmas",
    "Passagem para a Índia",
    "Estranhos no paraíso",
    "Os gritos do silêncio",
    "Um homem fora de série",
    "Memórias do cárcere",
    "O clube dos cinco",
    "A história oficial",
    "Entre dois amores",
    "A rosa púrpura do Cairo",
    "Um tempo para viver, um tempo para morrer",
    "Brazil - o filme",
    "O beijo da mulher aranha",
    "Terra tranquila",
    "Mishima - Uma vida em quatro tempos",
    "A honra do poderoso Prizzi",
    "Sem teto, nem lei",
    "A cor púrpura",
    "Caçador de assassinos",
    "Veludo azul",
    "Hannah e suas irmãs",
    "Ela quer tudo",
    "O declínio do império americano",
    "A mosca",
    "Aliens - o resgate",
    "Curtindo a vida adoidado",
    "Daunbailó",
    "Uma janela para o amor",
    "Filhos do silêncio",
    "Caravaggio",
    "Tampopo",
    "Peking Opera Blues",
    "Salvador, o martírio de um povo",
    "Top Gun - ases indomáveis",
    "Sherman's march",
    "The horse thief",
    "Yellen - A luz",
    "Asas do desejo",
    "Projeto China 2 - a vingança",
    "A festa de Babette",
    "Arizona nunca mais",
    "Os desajustados",
    "Bom dia, Vietnã",
    "Adeus, meninos",
    "Nos bastidores da notícia",
    "Dona-de-casa",
    "Feitiço da Lua",
    "Os intocáveis",
    "O sorgo vermelho",
    "Os vivos e os mortos",
    "Atração fatal",
    "Uma história chinesa de fantasmas",
    "Mulheres à beira de um ataque de nervos",
    "O silêncio do lago",
    "Sorte no amor",
    "Ariel",
    "A tênue linha da morte",
    "Akira",
    "Hotel Terminus: The life and times of Klaus Barbie",
    "Um peixe chamado Wanda",
    "Corra que a polícia vem aí!",
    "Quero ser grande",
    "Ligações perigosas",
    "Paisagem na neblina",
    "Decálogo",
    "Uma história do vento",
    "Uma cilada para Roger Rabbit",
    "Rain Man",
    "Um assunto de mulheres",
    "Afogando em números",
    "Alice",
    "Ilha das flores",
    "Batman",
    "Harry e Sally - feitos um para o outro",
    "Crimes e pecados",
    "O cozinheiro, o ladrão, sua mulher e o amante",
    "Drugstore cowboy",
    "Meu pé esquerdo",
    "O matador",
    "Faça a coisa certa",
    "Roger & Eu",
    "Tempo de glória",
    "Síndrome astênica",
    "Sexo, mentiras e videotape",
    "Digam o que quiserem",
    "A incrível verdade",
    "A cidade das tristezas",
    "No fear, no die",
    "O reverso da fortuna",
    "Alucinações do passado",
    "O rei de Nova York",
    "Filhos da guerra",
    "Uma linda mulher",
    "Arcanjo",
    "Confiança",
    "Close-up",
    "Edward mãos de tesoura",
    "Henry - o retrato de um assassino",
    "O vingador do futuro",
    "Era uma vez na China",
    "Os donos da rua",
    "Lanternas vermelhas",
    "Delicatessen",
    "A brighter summer day",
    "Mistérios e paixões",
    "A bela intrigante",
    "O juízo final",
    "Garotos de programa",
    "Thelma & Louise",
    "JFK - a pergunta que não quer calar",
    "Slacker",
    "Tongues untied",
    "Francis Ford Coppola - O Apocalipse de um cineasta",
    "A dupla vida de Veronique",
    "Vem dançar comigo",
    "Skinheads - A força branca",
    "O sucesso a qualquer preço",
    "Aileen Wuornos - The selling of a serial killer",
    "Conto de inverno",
    "The actress",
    "Aconteceu perto da sua casa",
    "Traídos pelo desejo",
    "Adeus, minha concubina",
    "O gênio e excêntrico Glenn Gould",
    "Short cuts - cenas da vida",
    "Filadélfia",
    "Mestre das marionetes",
    "Jurassic Park - parque dos dinossauros",
    "A liberdade é azul",
    "O piano",
    "O sonho azul",
    "O banquete de casamento",
    "Priscilla, a Rainha do deserto",
    "A fraternidade é vermelha",
    "Basquete Blues",
    "Forrest Gump - o contador de histórias",
    "O balconista",
    "Quatro casamentos e um funeral",
    "Assassinos por natureza",
    "O poder da sedução",
    "Pulp fiction - tempo de violência",
    "Rosas selvagens",
    "Amores expressos",
    "Crumb",
    "Sátántangó",
    "Através das oliveiras",
    "Almas gêmeas",
    "O casamento de Muriel",
    "O Reino",
    "Babe, o porquinho atrapalhado",
    "Deseret",
    "A salvo",
    "Zero Kelvin - Sem limites",
    "As Patricinhas de Beverly Hills",
    "Cortina de fumaça",
    "O balão branco",
    "Seven - os sete crimes capitais",
    "Underground - mentiras de guerra",
    "The brave heart will take the bride",
    "Entre a inocência e o crime",
    "Dead man",
    "Fargo - uma comédia de erros",
    "Três vidas e uma só morte",
    "Shine - Brilhante",
    "Ondas do destino",
    "Independence day",
    "Segredos e mentiras",
    "Gabbeh",
    "A estrela solitária",
    "Pânico",
    "O paciente inglês",
    "Los Angeles - cidade proibida",
    "Tempestade de gelo",
    "O doce amanhã",
    "Violência gratuita",
    "Gosto de cereja",
    "Preso na escuridão",
    "Festa de família",
    "Buffalo '66",
    "Três é demais",
    "Corra, Lola, corra",
    "Pi",
    "Felicidade",
    "Além da linha vermelha",
    "Ringu - o primeiro chamado",
    "Central do Brasil",
    "Magnólia",
    "Bom trabalho",
    "A entrevista",
    "A bruxa de Blair",
    "Três reis",
    "Tudo sobre minha mãe",
    "Quero ser John Malkovich",
    "Os catadores e eu",
    "O dia do perdão",
    "As coisas simples da vida",
    "O tigre e o dragão",
    "Dançando no escuro",
    "A caminho de Kandahar",
    "O senhor dos anéis",
    "A irmandade do anel",
    "As duas torres",
    "O retorno do Rei",
    "Distante",
    "Fale com ela",
    "A melhor juventude",
    "Kill Bill vol. 1",
    "Adeus, Lênin!",
    "Contra a parede",
    "A queda - as últimas horas de Hitler",
    "Paradise Now",
    "O segredo de Brokeback Mountain",
    "Infância roubada",
    "Pequena Miss Sunshine",
    "Apenas uma vez",
    "Borat",
    "Apocalypto",
    "O escafandro e a borboleta",
    "Piaf, um hino ao amor",
    "Onde os fracos não tem vez",
    "Os invencíveis",
    "Gomorra",
    "Quem quer ser um milionário?",
    "Anvil! A história de Anvil",
    "Deixa ela entrar",
    "Guerra ao terror",
    "Se beber, não case",
    "Aquário",
    "A fita branca",
    "Distrito 9",
    "In the loop",
    "Homens e Deuses",
    "Cisne Negro",
    "Quatro leões",
    "A rede social",
    "O discurso do Rei",
    "Bravura indômita"
}; // FILMES

const char *const diretores[] = {
    "Alfred Hitchcock",
    "Orson Welles",
    "John Ford",
    "Howard Hawks",
    "Martin Scorsese",
    "Akira Kurosawa",
    "Buster Keaton",
    "Ingmar Bergman",
    "Frank Capra",
    "Federico Fellini",
    "Steven Spielberg",
    "Jean Renoir",
    "John Huston",
    "Luis Buñuel",
    "D. W. Griffith",
    "Ernst Lubitsch",
    "Robert Altman",
    "George Cukor",
    "Woody Allen",
    "Vicente Minnelli",
    "Francis Ford Coppola",
    "Michael Powell",
    "Stanley Kubrick",
    "Billy Wilder",
    "Satyajit Ray",
    "Roman Polanski",
    "François Truffaut",
    "Preston Sturges",
    "Sergei Eisenstein",
    "Fritz Lang",
    "Jean-Luc Godard",
    "Sam Peckinpah",
    "F. W. Murnau",
    "David Lean",
    "Werner Herzog",
    "Nicholas Ray",
    "Josef Von Sterberg",
    "Douglas Sirk",
    "Max Ophuls",
    "Louis Malle",
    "Sergio Leone",
    "Sidney Lumet",
    "Oliver Stone",
    "Bernardo Bertolucci",
    "Jonathan Demme",
    "Jacques Tati",
    "Otto Preminger",
    "Spike Lee",
    "Tim Burton",
    "Jerry Lewis",
    "Jon Favreau",
    "Ben Affleck",
    "Joss Whedon",
    "George Lucas",
    "Zack Snyder",
    "Christopher Nolan",
    "Sam Raimi",
    "James Wan",
    "Patty Jenkins",
    "Anthony Russo",
    "Joe Russo",
    "Lilly Wachowski",
    "Lana Wachowski",
    "Jonh Krasinsky",
    "Marc Forster",
    "Jordan Peele",
    "James Cameron",
    "M. Night Shyamalan",
    "Denis Villeneuve",
    "Richard Linklater",
    "Guilhermo Del Toro",
}; // DIRETORES

const char *const paises[] = {
    "Andorra",
    "Emirados Árabes Unidos",
    "Afeganistão",
    "Antígua e Barbuda",
    "Anguilla",
    "Albânia",
    "Armênia",
    "Angola",
    "Antártica",
    "Argentina",
    "Samoa Americana",
    "Áustria",
    "Austrália",
    "Aruba",
    "Azerbaijão",
    "Bósnia e Herzegovina",
    "Barbados",
    "Bangladesh",
    "Bélgica",
    "Burkina Faso",
    "Bulgária",
    "Barém",
    "Burundi",
    "Benin",
    "São Bartolomeu",
    "Bermuda",
    "Brunei",
    "Bolívia",
    "Brasil",
    "Bahamas",
    "Butão",
    "Ilha Bouvet",
    "Botswana",
    "Belarus",
    "Belize",
    "Canadá",
    "Ilhas Cocos (Keeling)",
    "Congo, República Democrática do",
    "República Centro-Africana",
    "Congo, República do",
    "Suíça",
    "Costa do Marfim",
    "Ilhas Cook",
    "Chile",
    "Camarões",
    "China",
    "Colômbia",
    "Costa Rica",
    "Cuba",
    "Cabo Verde",
    "Curaçao",
    "Ilha Christmas",
    "Chipre",
    "República Tcheca",
    "Alemanha",
    "Djibuti",
    "Dinamarca",
    "Dominica",
    "República Dominicana",
    "Argélia",
    "Equador",
    "Estônia",
    "Egito",
    "Saara Ocidental",
    "Eritréia",
    "Espanha",
    "Etiópia",
    "Finlândia",
    "Fiji",
    "Ilhas Falkland (Malvinas)",
    "Micronésia, Estados Federados da",
    "Ilhas Feroe",
    "França",
    "França Metropolitana",
    "Gabão",
    "Reino Unido",
    "Grenada",
    "Geórgia",
    "Guiana Francesa",
    "Guernsey",
    "Gana",
    "Gibraltar",
    "Greenland",
    "Gâmbia",
    "Guiné",
    "Guadelupe",
    "Guiné Equatorial",
    "Grécia",
    "Geórgia do Sul e Ilhas",
    "Guatemala",
    "Guam",
    "Guiné-Bissau",
    "Guiana",
    "Hong Kong",
    "Ilhas Heard and McDonald",
    "Honduras",
    "Croácia",
    "Haiti",
    "Hungria",
    "Indonésia",
    "Irlanda",
    "Israel",
    "Ilha de Man",
    "Índia",
    "Iraque",
    "Irã",
    "Islândia",
    "Itália",
    "Jersey",
    "Jamaica",
    "Jordânia",
    "Japão",
    "Quênia",
    "Quirguistão",
    "Camboja",
    "Kiribati",
    "Cômoros",
    "São Cristóvão e Nevis",
    "Coreia do Norte",
    "Coreia do Sul",
    "Kuwait",
    "Ilhas Caiman",
    "Cazaquistão",
    "Laos",
    "Líbano",
    "Santa Lúcia",
    "Liechtenstein",
    "Sri Lanka",
    "Libéria",
    "Lesoto",
    "Lituânia",
    "Luxemburgo",
    "Letônia",
    "Líbia",
    "Marrocos",
    "Mônaco",
    "Moldova",
    "Montenegro",
    "Saint Martin",
    "Madagascar",
    "Ilhas Marshall",
    "Macedônia",
    "Mali",
    "Birmânia",
    "Mongólia",
    "Macao",
    "Ilhas Marianas do Norte",
    "Martinica",
    "Mauritânia",
    "Montserrat",
    "Malta",
    "Ilhas Maurício",
    "Maldivas",
    "Malawi",
    "México",
    "Malásia",
    "Moçambique",
    "Namíbia",
    "Nova Caledônia",
    "Níger",
    "Ilha Norfolk",
    "Nigéria",
    "Nicarágua",
    "Holanda",
    "Noruega",
    "Nepal",
    "Nauru",
    "Niue",
    "Nova Zelândia",
    "Omã",
    "Panamá",
    "Peru",
    "Polinésia Francesa",
    "Papua Nova Guiné",
    "Filipinas",
    "Paquistão",
    "Polônia",
    "Saint Pierre e Miquelon",
    "Ilhas Pitcairn",
    "Porto Rico",
    "Faixa de Gaza",
    "Cisjordânia",
    "Portugal",
    "Palau",
    "Paraguai",
    "Qatar",
    "Reunião",
    "Romênia",
    "Sérvia",
    "Rússia",
    "Ruanda",
    "Arábia Saudita",
    "Ilhas Salomão",
    "Seicheles",
    "Sudão",
    "Suécia",
    "Cingapura",
    "Eslovênia",
    "Svalbard",
    "Eslováquia",
    "Serra Leoa",
    "San Marino",
    "Senegal",
    "Somália",
    "Suriname",
    "Sudão do Sul",
    "São Tomé e Príncipe",
    "El Salvador",
    "São Martinho",
    "Síria",
    "Suazilândia",
    "Ilhas Turks e Caicos",
    "Chad",
    "Sul da França e Antártica",
    "Togo",
    "Tailândia",
    "Tadjiquistão",
    "Toquelau",
    "Timor-Leste",
    "Turcomenistão",
    "Tunísia",
    "Tonga",
    "Turquia",
    "Trinidad e Tobago",
    "Tuvalu",
    "Taiwan",
    "Tanzânia",
    "Ucrânia",
    "Uganda",
    "Ilhas Menores Distantes dos Estados Unidos",
    "Estados Unidos",
    "Uruguai",
    "Uzbequistão",
    "Santa Sé (Cidade do Vaticano)",
    "São Vicente e Granadinas",
    "Venezuela",
    "Ilhas Virgens Britânicas",
    "Ilhas Virgens Americanas",
    "Vietnã",
    "Vanuatu",
    "Ilhas Wallis e Futuna",
    "Samoa",
    "Kosovo",
    "Iêmen",
    "Maiote",
    "África do Sul",
    "Zâmbia",
    "Zimbábue",
}; // PAISES

const unsigned long quant_filmes = sizeof(filmes)/sizeof(filmes[0]);
const unsigned long quant_diretores = sizeof(diretores)/sizeof(diretores[0]);
const unsigned long quant_paises = sizeof(paises)/sizeof(paises[0]);
